Repository aws-powertools/powertools-lambda-java, pull requests merged in 2021-07, with the labels that each got.

#457 chore: prep release 1.7.0
  CHANGELOG.md
  README.md
  docs/index.md
  docs/utilities/batch.md
  docs/utilities/parameters.md
  docs/utilities/sqs_large_message_handling.md
  docs/utilities/validation.md
  example/HelloWorldFunction/build.gradle
  example/HelloWorldFunction/pom.xml
  pom.xml
  powertools-core/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-sqs/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
Labels: size/L

#459 chore: prep release 1.7.1
  CHANGELOG.md
  README.md
  docs/index.md
  docs/utilities/batch.md
  docs/utilities/parameters.md
  docs/utilities/sqs_large_message_handling.md
  docs/utilities/validation.md
  example/HelloWorldFunction/build.gradle
  example/HelloWorldFunction/pom.xml
  pom.xml
  powertools-core/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-sqs/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
Labels: size/L

#479 Fix imports @Logging after upgrade
  docs/core/logging.md
Labels: size/XS

#484 chore: Logging and SQS utility Optimisations
  powertools-core/src/main/java/software/amazon/lambda/powertools/core/internal/LambdaHandlerProcessor.java
  powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/LoggingUtils.java
  powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/LambdaLoggingAspect.java
  powertools-metrics/src/main/java/software/amazon/lambda/powertools/metrics/internal/LambdaMetricsAspect.java
  powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/SqsUtils.java
Labels: size/M
