Repository aws-powertools/powertools-lambda-java, pull requests merged in 2021-12, with the labels that each got.

#647 chore: prep release 1.8.1
  CHANGELOG.md
  README.md
  docs/index.md
  docs/utilities/batch.md
  docs/utilities/custom_resources.md
  docs/utilities/parameters.md
  docs/utilities/sqs_large_message_handling.md
  docs/utilities/validation.md
  example/HelloWorldFunction/build.gradle
  example/HelloWorldFunction/pom.xml
  pom.xml
  powertools-cloudformation/pom.xml
  powertools-core/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-sqs/pom.xml
  powertools-test-suite/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
Labels: size/L

#653 chore: prep release 1.8.2
  CHANGELOG.md
  README.md
  docs/index.md
  docs/utilities/batch.md
  docs/utilities/custom_resources.md
  docs/utilities/parameters.md
  docs/utilities/sqs_large_message_handling.md
  docs/utilities/validation.md
  example/HelloWorldFunction/build.gradle
  example/HelloWorldFunction/pom.xml
  pom.xml
  powertools-cloudformation/pom.xml
  powertools-core/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-sqs/pom.xml
  powertools-test-suite/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
Labels: size/L

#655 feat(tracing): add service annotation
  docs/core/tracing.md
  powertools-tracing/src/main/java/software/amazon/lambda/powertools/tracing/internal/LambdaTracingAspect.java
  powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/internal/LambdaTracingAspectTest.java
Labels: size/M

#656 chore: Update docs to reflect latest gradle plugin fix
  docs/index.md
  example/HelloWorldFunction/build.gradle
Labels: size/XS

#664 chore: localise abstract json layout implementation
  powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/AbstractJacksonLayoutCopy.java
  powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/JacksonFactoryCopy.java
  powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/LambdaJsonLayout.java
  spotbugs-exclude.xml
Labels: size/XL

#666 chore: prep release 1.9.0
  CHANGELOG.md
  README.md
  docs/index.md
  docs/utilities/batch.md
  docs/utilities/custom_resources.md
  docs/utilities/parameters.md
  docs/utilities/sqs_large_message_handling.md
  docs/utilities/validation.md
  example/HelloWorldFunction/build.gradle
  example/HelloWorldFunction/pom.xml
  pom.xml
  powertools-cloudformation/pom.xml
  powertools-core/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-sqs/pom.xml
  powertools-test-suite/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
Labels: size/L

#667 fix: support batch size greater than 10 processing
  powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/internal/BatchContext.java
  powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/SqsUtilsBatchProcessorTest.java
  powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/internal/SqsMessageBatchProcessorAspectTest.java
  powertools-sqs/src/test/resources/sampleSqsBatchEventBatchSize25.json
Labels: size/XL

#670 feat: Json layout modern implementation
  docs/core/logging.md
  pom.xml
  powertools-logging/pom.xml
  powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/AbstractJacksonLayoutCopy.java
  powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/JacksonFactoryCopy.java
  powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/LambdaJsonLayout.java
  powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/PowertoolsResolver.java
  powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/PowertoolsResolverFactory.java
  powertools-logging/src/main/resources/LambdaEcsLayout.json
  powertools-logging/src/main/resources/LambdaJsonLayout.json
  powertools-logging/src/main/resources/log4j2.component.properties
  powertools-logging/src/test/resources/log4j2.xml
Labels: size/L

#671 chore: prep release 1.10.0
  CHANGELOG.md
  README.md
  docs/index.md
  docs/utilities/batch.md
  docs/utilities/custom_resources.md
  docs/utilities/parameters.md
  docs/utilities/sqs_large_message_handling.md
  docs/utilities/validation.md
  example/HelloWorldFunction/build.gradle
  example/HelloWorldFunction/pom.xml
  pom.xml
  powertools-cloudformation/pom.xml
  powertools-core/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-sqs/pom.xml
  powertools-test-suite/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
Labels: size/L
