Repository aws-powertools/powertools-lambda-java, pull requests merged in 2022-01, with the labels that each got.

#679 chore(docs): use free fair gradle aspect plugin
  docs/index.md
  docs/utilities/batch.md
  docs/utilities/custom_resources.md
  docs/utilities/parameters.md
  docs/utilities/sqs_large_message_handling.md
  docs/utilities/validation.md
Labels: size/M

#684 master: Upgrading Powertool to version 1.10.1 for Log4j version upgrade
  CHANGELOG.md
  README.md
  docs/index.md
  docs/utilities/batch.md
  docs/utilities/custom_resources.md
  docs/utilities/parameters.md
  docs/utilities/sqs_large_message_handling.md
  docs/utilities/validation.md
  example/HelloWorldFunction/build.gradle
  example/HelloWorldFunction/pom.xml
  pom.xml
  powertools-cloudformation/pom.xml
  powertools-core/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-sqs/pom.xml
  powertools-test-suite/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
Labels: size/L

#680 chore(docs): Add FAQs section to docs with information about Lombok support.
  docs/FAQs.md
  mkdocs.yml
Labels: size/S

#696 chore: Automate release prep
  .github/workflows/release-prep.yml
  docs/Dockerfile
  docs/index.md
  docs/utilities/batch.md
  docs/utilities/custom_resources.md
  docs/utilities/parameters.md
  docs/utilities/sqs_large_message_handling.md
  docs/utilities/validation.md
  mkdocs.yml
Labels: size/L

#698 feat(tracing): ability to override object mapper
  docs/core/tracing.md
  powertools-tracing/src/main/java/software/amazon/lambda/powertools/tracing/TracingUtils.java
  powertools-tracing/src/main/java/software/amazon/lambda/powertools/tracing/internal/LambdaTracingAspect.java
  powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/handlers/PowerTracerToolEnabledForResponseWithCustomMapper.java
  powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/internal/LambdaTracingAspectTest.java
  spotbugs-exclude.xml
Labels: size/L

#701 chore:Prep release 1.10.2
  CHANGELOG.md
  README.md
  example/HelloWorldFunction/build.gradle
  example/HelloWorldFunction/pom.xml
  mkdocs.yml
  pom.xml
  powertools-cloudformation/pom.xml
  powertools-core/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-sqs/pom.xml
  powertools-test-suite/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
Labels: size/M

#703 fix(gradle): Fix gradle example and docs to work with java 12+
  docs/index.md
  example/HelloWorldFunction/build.gradle
  example/HelloWorldFunction/gradle/wrapper/gradle-wrapper.properties
  example/HelloWorldFunction/pom.xml
Labels: size/M
