Repository aws-powertools/powertools-lambda-java, pull requests merged in 2022-03, with the labels that each got.

#772 chore: remove examples from the project as it was moved to aws-lambda…
  example/HelloWorldFunction/build.gradle
  example/HelloWorldFunction/gradle.properties
  example/HelloWorldFunction/gradle/wrapper/gradle-wrapper.jar
  example/HelloWorldFunction/gradle/wrapper/gradle-wrapper.properties
  example/HelloWorldFunction/gradlew
  example/HelloWorldFunction/gradlew.bat
  example/HelloWorldFunction/pom.xml
  example/HelloWorldFunction/settings.gradle
  example/HelloWorldFunction/src/main/java/helloworld/AppParams.java
  example/HelloWorldFunction/src/main/java/helloworld/AppValidation.java
  example/HelloWorldFunction/src/main/java/helloworld/MyObject.java
  example/HelloWorldFunction/src/main/resources/log4j2.xml
  example/HelloWorldFunction/src/main/resources/schema.json
  example/README.md
  example/events/event.json
  example/events/eventSqs.json
  example/template.yaml
Labels: size/XXL

#775 chore:Prep release 1.12.0
  CHANGELOG.md
  README.md
  mkdocs.yml
  pom.xml
  powertools-cloudformation/pom.xml
  powertools-core/pom.xml
  powertools-idempotency/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-serialization/pom.xml
  powertools-sqs/pom.xml
  powertools-test-suite/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
Labels: size/M

#781 Documentation: Changed project name for consistency
  README.md
  docs/index.md
  mkdocs.yml
  pom.xml
  powertools-cloudformation/pom.xml
  powertools-core/pom.xml
  powertools-idempotency/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-serialization/pom.xml
  powertools-sqs/pom.xml
  powertools-test-suite/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
Labels: size/M

#789 chore(docs): additional rename of project name (#781)
  docs/index.md
Labels: size/XS

#796 fix: disable idempotency doesn't disable dynamodb client creation in persistent store
  powertools-idempotency/src/main/java/software/amazon/lambda/powertools/idempotency/internal/IdempotentAspect.java
  powertools-idempotency/src/main/java/software/amazon/lambda/powertools/idempotency/persistence/DynamoDBPersistenceStore.java
  powertools-idempotency/src/test/java/software/amazon/lambda/powertools/idempotency/persistence/DynamoDBPersistenceStoreTest.java
Labels: size/S
