Repository aws-powertools/powertools-lambda-java, pull requests merged in 2022-02, with the labels that each got.

#731 fix: Prevent message to be marked as success if failed sending to DLQ
  docs/utilities/batch.md
  powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/internal/BatchContext.java
  powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/internal/SqsMessageBatchProcessorAspectTest.java
Labels: size/M

#733 chore: move core utilities example to aws-samples/aws-lambda-powertools-examples
  example/HelloWorldFunction/src/main/java/helloworld/App.java
  example/HelloWorldFunction/src/main/java/helloworld/AppStream.java
  example/template.yaml
Labels: size/L

#734 chore:Prep release 1.10.3
  CHANGELOG.md
  README.md
  example/HelloWorldFunction/build.gradle
  example/HelloWorldFunction/pom.xml
  mkdocs.yml
  pom.xml
  powertools-cloudformation/pom.xml
  powertools-core/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-sqs/pom.xml
  powertools-test-suite/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
Labels: size/M

#735 chore(docs): Clarify test config needed for Tracing module
  docs/core/tracing.md
Labels: size/M

#754 chore: remove SQS and Idempotency examples
  example/HelloWorldFunction/build.gradle
  example/HelloWorldFunction/pom.xml
  example/HelloWorldFunction/src/main/java/helloworld/AppIdempotency.java
  example/HelloWorldFunction/src/main/java/helloworld/AppSqsEvent.java
  example/HelloWorldFunction/src/main/java/helloworld/AppSqsEventUtil.java
  example/template.yaml
Labels: size/L

#759 fix: #758
  powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/BaseProvider.java
  powertools-parameters/src/test/java/software/amazon/lambda/powertools/parameters/SSMProviderTest.java
Labels: size/M

#763 fix(docs): fix title for custom resources page
  docs/utilities/custom_resources.md
Labels: size/XS
