Repository aws-powertools/powertools-lambda-java, pull requests merged in 2022-11, with the labels that each got.

#960 fix: envelope is not taken into account with built-in types
  powertools-validation/pom.xml
  powertools-validation/src/main/java/software/amazon/lambda/powertools/validation/ValidationUtils.java
  powertools-validation/src/main/java/software/amazon/lambda/powertools/validation/internal/ValidationAspect.java
  powertools-validation/src/test/java/software/amazon/lambda/powertools/validation/handlers/SQSWithCustomEnvelopeHandler.java
  powertools-validation/src/test/java/software/amazon/lambda/powertools/validation/handlers/SQSWithWrongEnvelopeHandler.java
  powertools-validation/src/test/java/software/amazon/lambda/powertools/validation/internal/ValidationAspectTest.java
  powertools-validation/src/test/resources/sqs_message.json
Labels: size/L

#984 Fix for #577: Some code suggestion from CodeGuru
  powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/cache/DataStore.java
  powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/internal/BatchContext.java
  powertools-validation/src/main/java/software/amazon/lambda/powertools/validation/ValidationUtils.java
Labels: size/M

#976 docs: add missing grammar article
  docs/utilities/sqs_large_message_handling.md
Labels: size/XS

#998 fix: compilation warning with SqsLargeMessageAspect on gradle
  powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/LambdaLoggingAspect.java
Labels: size/XS
