Repository aws-powertools/powertools-lambda-java, pull requests merged in 2023-06, with the labels that each got.

#1169 chore: rename project from Powertools to Powertools for AWS Lambda (Java)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/maintenance.yml
  .github/ISSUE_TEMPLATE/rfc.md
  .github/ISSUE_TEMPLATE/share_your_work.yml
  .github/ISSUE_TEMPLATE/support_powertools.yml
  CHANGELOG.md
  README.md
  docs/FAQs.md
  docs/core/logging.md
  docs/core/tracing.md
  docs/index.md
  docs/utilities/custom_resources.md
  docs/utilities/idempotency.md
  docs/utilities/serialization.md
  examples/README.md
  examples/pom.xml
  examples/powertools-examples-core/README.md
  examples/powertools-examples-core/pom.xml
  examples/powertools-examples-core/template.yaml
  examples/powertools-examples-idempotency/README.md
  examples/powertools-examples-idempotency/pom.xml
  examples/powertools-examples-parameters/README.md
  examples/powertools-examples-parameters/pom.xml
  examples/powertools-examples-serialization/README.md
  examples/powertools-examples-serialization/pom.xml
  examples/powertools-examples-sqs/pom.xml
  examples/powertools-examples-sqs/template.yaml
  examples/powertools-examples-validation/README.md
  examples/powertools-examples-validation/pom.xml
  mkdocs.yml
  pom.xml
  powertools-cloudformation/src/main/java/software/amazon/lambda/powertools/cloudformation/AbstractCustomResourceHandler.java
  powertools-cloudformation/src/main/java/software/amazon/lambda/powertools/cloudformation/Response.java
  powertools-core/pom.xml
  powertools-e2e-tests/README.md
  powertools-e2e-tests/handlers/idempotency/pom.xml
  powertools-e2e-tests/handlers/logging/pom.xml
  powertools-e2e-tests/handlers/pom.xml
  powertools-idempotency/pom.xml
  powertools-idempotency/src/main/java/software/amazon/lambda/powertools/idempotency/internal/IdempotencyHandler.java
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/DynamoDbProvider.java
  powertools-serialization/pom.xml
  powertools-sqs/pom.xml
  powertools-test-suite/pom.xml
  powertools-tracing/pom.xml
  powertools-tracing/src/main/java/software/amazon/lambda/powertools/tracing/Tracing.java
  powertools-validation/pom.xml
Labels: size/L

#1201 fix: missing idempotency key should not persist any data
  docs/utilities/idempotency.md
  powertools-idempotency/src/main/java/software/amazon/lambda/powertools/idempotency/internal/IdempotencyHandler.java
  powertools-idempotency/src/main/java/software/amazon/lambda/powertools/idempotency/persistence/BasePersistenceStore.java
  powertools-idempotency/src/test/java/software/amazon/lambda/powertools/idempotency/persistence/BasePersistenceStoreTest.java
Labels: size/M

#1171 chore: Change repo URL to the new location
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/maintenance.yml
  .github/ISSUE_TEMPLATE/rfc.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/release-prep.yml
  CHANGELOG.md
  README.md
  docs/core/logging.md
  docs/index.md
  docs/utilities/idempotency.md
  examples/powertools-examples-core/README.md
  examples/powertools-examples-idempotency/README.md
  examples/powertools-examples-parameters/README.md
  examples/powertools-examples-serialization/README.md
  examples/powertools-examples-validation/README.md
  mkdocs.yml
  pom.xml
  powertools-cloudformation/pom.xml
  powertools-core/pom.xml
  powertools-e2e-tests/pom.xml
  powertools-idempotency/README.md
  powertools-idempotency/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/DynamoDbProvider.java
  powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/ParamManager.java
  powertools-serialization/pom.xml
  powertools-sqs/pom.xml
  powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/SqsUtils.java
  powertools-test-suite/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
Labels: size/L

#1191 chore: add all java versions and use corretto for build
  .github/workflows/build.yml
Labels: size/S

#1175 chore: E2E tests GitHub action
  .github/workflows/run-e2e-tests.yml
  pom.xml
  powertools-e2e-tests/pom.xml
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/IdempotencyE2ET.java
Labels: size/M

#1190 test: Roll SLF4J log4j bindings to v2
  pom.xml
  powertools-logging/pom.xml
  powertools-serialization/pom.xml
Labels: size/XS

#1225 fix: e2e tests on JDK8
  .github/workflows/run-e2e-tests.yml
  powertools-e2e-tests/handlers/parameters/pom.xml
  powertools-e2e-tests/handlers/parameters/src/main/java/software/amazon/lambda/powertools/e2e/Function.java
  powertools-e2e-tests/handlers/pom.xml
  powertools-e2e-tests/pom.xml
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/ParametersE2ET.java
Labels: size/L

#1227 chore: removing logback from all components
  pom.xml
  powertools-cloudformation/pom.xml
  powertools-cloudformation/src/test/resources/logback.xml
  powertools-e2e-tests/pom.xml
  powertools-e2e-tests/src/test/resources/log4j2.xml
  powertools-e2e-tests/src/test/resources/logback-test.xml
Labels: size/M

#1238 chore: Update docs base origin url
  docs/index.md
  docs/javascript/extra.js
  examples/powertools-examples-core/template.yaml
  examples/powertools-examples-sqs/template.yaml
  powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/AppConfigProvider.java
Labels: size/S

#1240 [fix] Decouple samples from the parent pom
  .github/workflows/build.yml
  examples/README.md
  examples/pom.xml
  examples/powertools-examples-core/pom.xml
  examples/powertools-examples-idempotency/pom.xml
  examples/powertools-examples-parameters/pom.xml
  examples/powertools-examples-serialization/pom.xml
  examples/powertools-examples-sqs/pom.xml
  examples/powertools-examples-validation/pom.xml
Labels: size/XL

#1236 chore: cleanup spotbugs maven profiles
  .github/workflows/build.yml
  .github/workflows/publish.yml
  .github/workflows/run-e2e-tests.yml
  pom.xml
Labels: size/M

#1249 chore:Prep release 1.16.0
  CHANGELOG.md
  README.md
  examples/pom.xml
  examples/powertools-examples-core/pom.xml
  examples/powertools-examples-idempotency/pom.xml
  examples/powertools-examples-parameters/pom.xml
  examples/powertools-examples-serialization/pom.xml
  examples/powertools-examples-sqs/pom.xml
  examples/powertools-examples-validation/pom.xml
  mkdocs.yml
  pom.xml
  powertools-cloudformation/pom.xml
  powertools-core/pom.xml
  powertools-e2e-tests/handlers/pom.xml
  powertools-e2e-tests/pom.xml
  powertools-idempotency/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-serialization/pom.xml
  powertools-sqs/pom.xml
  powertools-test-suite/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
Labels: size/M

#1252 chore: update poms to next dev version 1.17.0-SNAPSHOT
  README.md
  examples/pom.xml
  examples/powertools-examples-core/pom.xml
  examples/powertools-examples-idempotency/pom.xml
  examples/powertools-examples-parameters/pom.xml
  examples/powertools-examples-serialization/pom.xml
  examples/powertools-examples-sqs/pom.xml
  examples/powertools-examples-validation/pom.xml
  mkdocs.yml
  pom.xml
  powertools-cloudformation/pom.xml
  powertools-core/pom.xml
  powertools-e2e-tests/handlers/pom.xml
  powertools-e2e-tests/pom.xml
  powertools-idempotency/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-serialization/pom.xml
  powertools-sqs/pom.xml
  powertools-test-suite/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
Labels: size/M

#1253 fix: examples shouldn't be deployed to mvn central
  examples/powertools-examples-core/pom.xml
  examples/powertools-examples-idempotency/pom.xml
  examples/powertools-examples-parameters/pom.xml
  examples/powertools-examples-serialization/pom.xml
  examples/powertools-examples-sqs/pom.xml
  examples/powertools-examples-validation/pom.xml
Labels: size/S
