Repository aws-powertools/powertools-lambda-java, pull requests merged in 2023-11, with the labels that each got.

#1503 fix: get trace id from system property when env var is not set
  powertools-core/src/main/java/software/amazon/lambda/powertools/core/internal/LambdaConstants.java
  powertools-core/src/main/java/software/amazon/lambda/powertools/core/internal/LambdaHandlerProcessor.java
  powertools-core/src/main/java/software/amazon/lambda/powertools/core/internal/SystemWrapper.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/LoggingE2ET.java
  powertools-logging/src/test/java/software/amazon/lambda/powertools/logging/internal/LambdaLoggingAspectTest.java
  powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/MetricsLoggerTest.java
  powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/internal/LambdaMetricsAspectTest.java
Labels: size/M

#1507 chore: removing dynamodb local from examples
  examples/powertools-examples-idempotency/pom.xml
Labels: size/XS

#1506 fix: null namespace should fallback to default namespace
  powertools-metrics/src/main/java/software/amazon/lambda/powertools/metrics/MetricsUtils.java
  powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/MetricsLoggerTest.java
Labels: size/M

#1510 feat: Add support for POWERTOOLS_LOGGER_LOG_EVENT
  docs/core/logging.md
  docs/index.md
  powertools-core/src/main/java/software/amazon/lambda/powertools/core/internal/LambdaHandlerProcessor.java
  powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/LambdaLoggingAspect.java
  powertools-logging/src/test/java/software/amazon/lambda/powertools/logging/handlers/PowerToolLogEventDisabled.java
  powertools-logging/src/test/java/software/amazon/lambda/powertools/logging/internal/LambdaLoggingAspectTest.java
Labels: size/L

#1512 chore: Addition of Warn Message If Invalid Annotation Key While Tracing #1511
  powertools-tracing/src/main/java/software/amazon/lambda/powertools/tracing/TracingUtils.java
  powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/TracingUtilsTest.java
Labels: size/M

#1514 feat: alc
  docs/core/logging.md
  powertools-logging/pom.xml
  powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/LambdaLoggingAspect.java
  powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/LambdaTimestampResolver.java
  powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/LambdaTimestampResolverFactory.java
  powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/LoggingConstants.java
  powertools-logging/src/main/resources/LambdaJsonLayout.json
  powertools-logging/src/test/java/org/apache/logging/log4j/core/layout/LambdaJsonLayoutTest.java
Labels: size/L

#1515 chore:Prep release 1.18.0
  CHANGELOG.md
  README.md
  examples/pom.xml
  examples/powertools-examples-batch/pom.xml
  examples/powertools-examples-cloudformation/pom.xml
  examples/powertools-examples-core/cdk/app/pom.xml
  examples/powertools-examples-core/cdk/infra/pom.xml
  examples/powertools-examples-core/gradle/build.gradle
  examples/powertools-examples-core/kotlin/build.gradle.kts
  examples/powertools-examples-core/sam/pom.xml
  examples/powertools-examples-core/serverless/pom.xml
  examples/powertools-examples-core/terraform/pom.xml
  examples/powertools-examples-idempotency/pom.xml
  examples/powertools-examples-parameters/pom.xml
  examples/powertools-examples-serialization/pom.xml
  examples/powertools-examples-sqs/pom.xml
  examples/powertools-examples-validation/pom.xml
  mkdocs.yml
  pom.xml
  powertools-batch/pom.xml
  powertools-cloudformation/pom.xml
  powertools-core/pom.xml
  powertools-e2e-tests/handlers/pom.xml
  powertools-e2e-tests/pom.xml
  powertools-idempotency/pom.xml
  powertools-large-messages/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-serialization/pom.xml
  powertools-sqs/pom.xml
  powertools-test-suite/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
Labels: size/L

#1516 chore: update version to next snapshot: 1-19.0-SNAPSHOT
  .github/workflows/pr_build.yml
  examples/pom.xml
  examples/powertools-examples-batch/pom.xml
  examples/powertools-examples-cloudformation/pom.xml
  examples/powertools-examples-core/cdk/infra/pom.xml
  examples/powertools-examples-core/gradle/build.gradle
  examples/powertools-examples-core/kotlin/build.gradle.kts
  examples/powertools-examples-core/sam/pom.xml
  examples/powertools-examples-core/serverless/pom.xml
  examples/powertools-examples-core/terraform/pom.xml
  examples/powertools-examples-idempotency/pom.xml
  examples/powertools-examples-parameters/pom.xml
  examples/powertools-examples-serialization/pom.xml
  examples/powertools-examples-sqs/pom.xml
  examples/powertools-examples-validation/pom.xml
  pom.xml
  powertools-batch/pom.xml
  powertools-cloudformation/pom.xml
  powertools-core/pom.xml
  powertools-e2e-tests/handlers/pom.xml
  powertools-e2e-tests/pom.xml
  powertools-idempotency/pom.xml
  powertools-large-messages/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-serialization/pom.xml
  powertools-sqs/pom.xml
  powertools-test-suite/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
Labels: size/M

#1518 fix: LargeMessageIdempotentE2ET Flaky
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/LargeMessageIdempotentE2ET.java
Labels: size/XS

#1517 test: e2e tests with java 21
  .github/workflows/run-e2e-tests.yml
  README.md
  docs/index.md
  powertools-e2e-tests/pom.xml
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/Infrastructure.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/JavaRuntime.java
Labels: size/M

#1520 docs: update doc for ALC
  docs/core/logging.md
Labels: size/M

#1519 chore: Testing java21 aspectj pre-release
  README.md
  docs/index.md
  pom.xml
  powertools-e2e-tests/handlers/logging/pom.xml
  powertools-e2e-tests/handlers/pom.xml
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/Infrastructure.java
Labels: size/L

#1526 chore: fix build configuration
  .github/workflows/run-e2e-tests.yml
Labels: size/S
