Repository aws-powertools/powertools-lambda-java, pull requests merged in 2023-03, with the labels that each got.

#1082 fix(cloudformation-module): Use physicalResourceId when not provided by custom resource
  pom.xml
  powertools-cloudformation/pom.xml
  powertools-cloudformation/src/main/java/software/amazon/lambda/powertools/cloudformation/AbstractCustomResourceHandler.java
  powertools-cloudformation/src/main/java/software/amazon/lambda/powertools/cloudformation/CloudFormationResponse.java
  powertools-cloudformation/src/main/java/software/amazon/lambda/powertools/cloudformation/Response.java
  powertools-cloudformation/src/test/java/software/amazon/lambda/powertools/cloudformation/CloudFormationIntegrationTest.java
  powertools-cloudformation/src/test/java/software/amazon/lambda/powertools/cloudformation/CloudFormationResponseTest.java
  powertools-cloudformation/src/test/java/software/amazon/lambda/powertools/cloudformation/handlers/NoPhysicalResourceIdSetHandler.java
  powertools-cloudformation/src/test/java/software/amazon/lambda/powertools/cloudformation/handlers/PhysicalResourceIdSetHandler.java
  powertools-cloudformation/src/test/java/software/amazon/lambda/powertools/cloudformation/handlers/RuntimeExceptionThrownHandler.java
  powertools-cloudformation/src/test/resources/logback.xml
Labels: size/L

#1094 maintenance: send coverage (jacoco) to codecov
  .github/workflows/build.yml
  README.md
  examples/pom.xml
  examples/powertools-examples-validation/pom.xml
  pom.xml
Labels: size/M

#1090 docs(cloudformation-module): Improve Docs
  docs/utilities/custom_resources.md
Labels: size/L

#1097 chore: update the project version to 1.15.0
  CHANGELOG.md
  README.md
  examples/pom.xml
  examples/powertools-examples-core/pom.xml
  examples/powertools-examples-idempotency/pom.xml
  examples/powertools-examples-parameters/pom.xml
  examples/powertools-examples-serialization/pom.xml
  examples/powertools-examples-sqs/pom.xml
  examples/powertools-examples-validation/pom.xml
  mkdocs.yml
  pom.xml
  powertools-cloudformation/pom.xml
  powertools-core/pom.xml
  powertools-idempotency/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-serialization/pom.xml
  powertools-sqs/pom.xml
  powertools-test-suite/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
Labels: size/M

#970 feat: end-to-end tests for core modules and idempotency
  pom.xml
  powertools-e2e-tests/README.md
  powertools-e2e-tests/handlers/idempotency/pom.xml
  powertools-e2e-tests/handlers/idempotency/src/main/java/software/amazon/lambda/powertools/e2e/Function.java
  powertools-e2e-tests/handlers/idempotency/src/main/java/software/amazon/lambda/powertools/e2e/Input.java
  powertools-e2e-tests/handlers/logging/pom.xml
  powertools-e2e-tests/handlers/logging/src/main/java/software/amazon/lambda/powertools/e2e/Function.java
  powertools-e2e-tests/handlers/logging/src/main/java/software/amazon/lambda/powertools/e2e/Input.java
  powertools-e2e-tests/handlers/logging/src/main/resources/log4j2.xml
  powertools-e2e-tests/handlers/metrics/pom.xml
  powertools-e2e-tests/handlers/metrics/src/main/java/software/amazon/lambda/powertools/e2e/Function.java
  powertools-e2e-tests/handlers/metrics/src/main/java/software/amazon/lambda/powertools/e2e/Input.java
  powertools-e2e-tests/handlers/pom.xml
  powertools-e2e-tests/handlers/tracing/pom.xml
  powertools-e2e-tests/handlers/tracing/src/main/java/software/amazon/lambda/powertools/e2e/Function.java
  powertools-e2e-tests/handlers/tracing/src/main/java/software/amazon/lambda/powertools/e2e/Input.java
  powertools-e2e-tests/handlers/tracing/src/main/resources/log4j2.xml
  powertools-e2e-tests/pom.xml
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/IdempotencyE2ET.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/LoggingE2ET.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/MetricsE2ET.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/TracingE2ET.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/Infrastructure.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/JavaRuntime.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/lambda/InvocationResult.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/lambda/LambdaInvoker.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/logging/InvocationLogs.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/metrics/MetricsFetcher.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/tracing/SegmentDocument.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/tracing/Trace.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/tracing/TraceFetcher.java
  powertools-e2e-tests/src/test/resources/logback-test.xml
Labels: size/XXL
