Repository aws-powertools/powertools-lambda-java, pull requests merged in 2023-07, with the labels that each got.

#1282 fix: ParamManager cannot provide default SSM & Secrets providers
  powertools-parameters/pom.xml
  powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/DynamoDbProvider.java
  powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/ParamManager.java
  powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/SSMProvider.java
  powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/SecretsProvider.java
  powertools-parameters/src/test/java/software/amazon/lambda/powertools/parameters/ParamManagerTest.java
Labels: size/L

#1287 docs: adding our customer references
  README.md
Labels: size/S

#1285 fix: idempotency timeout bug
  powertools-idempotency/src/main/java/software/amazon/lambda/powertools/idempotency/persistence/DataRecord.java
  powertools-idempotency/src/main/java/software/amazon/lambda/powertools/idempotency/persistence/DynamoDBPersistenceStore.java
  powertools-idempotency/src/test/java/software/amazon/lambda/powertools/idempotency/persistence/DynamoDBPersistenceStoreTest.java
Labels: size/M

#1294 docs: update README.md
  README.md
Labels: size/M

#1089 build(examples): Add example for the powertools-cloudformation module
  examples/pom.xml
  examples/powertools-examples-cloudformation/README.md
  examples/powertools-examples-cloudformation/infra/cdk/.gitignore
  examples/powertools-examples-cloudformation/infra/cdk/cdk.json
  examples/powertools-examples-cloudformation/infra/cdk/pom.xml
  examples/powertools-examples-cloudformation/infra/cdk/src/main/java/com/myorg/PowertoolsExamplesCloudformationCdkApp.java
  examples/powertools-examples-cloudformation/infra/cdk/src/main/java/com/myorg/PowertoolsExamplesCloudformationCdkStack.java
  examples/powertools-examples-cloudformation/infra/sam/events/create_event.json
  examples/powertools-examples-cloudformation/infra/sam/events/delete_event.json
  examples/powertools-examples-cloudformation/infra/sam/events/update_event.json
  examples/powertools-examples-cloudformation/infra/sam/template.yaml
  examples/powertools-examples-cloudformation/pom.xml
  examples/powertools-examples-cloudformation/src/main/java/helloworld/App.java
  examples/powertools-examples-cloudformation/src/main/resources/log4j2.xml
Labels: size/XL

#1296 chore:Prep release 1.16.1
  CHANGELOG.md
  README.md
  examples/pom.xml
  examples/powertools-examples-cloudformation/pom.xml
  examples/powertools-examples-core/pom.xml
  examples/powertools-examples-idempotency/pom.xml
  examples/powertools-examples-parameters/pom.xml
  examples/powertools-examples-serialization/pom.xml
  examples/powertools-examples-sqs/pom.xml
  examples/powertools-examples-validation/pom.xml
  mkdocs.yml
  pom.xml
  powertools-cloudformation/pom.xml
  powertools-core/pom.xml
  powertools-e2e-tests/handlers/pom.xml
  powertools-e2e-tests/pom.xml
  powertools-idempotency/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-serialization/pom.xml
  powertools-sqs/pom.xml
  powertools-test-suite/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
Labels: size/M

#1299 chore: update poms to SNAPSHOT version for dev
  examples/pom.xml
  examples/powertools-examples-cloudformation/pom.xml
  examples/powertools-examples-core/pom.xml
  examples/powertools-examples-idempotency/pom.xml
  examples/powertools-examples-parameters/pom.xml
  examples/powertools-examples-serialization/pom.xml
  examples/powertools-examples-sqs/pom.xml
  examples/powertools-examples-validation/pom.xml
  pom.xml
  powertools-cloudformation/pom.xml
  powertools-core/pom.xml
  powertools-e2e-tests/handlers/pom.xml
  powertools-e2e-tests/pom.xml
  powertools-idempotency/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-serialization/pom.xml
  powertools-sqs/pom.xml
  powertools-test-suite/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
Labels: size/M

#1291 docs: Started cleaning up example doc
  docs/index.md
  examples/README.md
  examples/powertools-examples-cloudformation/README.md
  examples/powertools-examples-core/README.md
  examples/powertools-examples-idempotency/README.md
  examples/powertools-examples-idempotency/src/main/java/helloworld/App.java
  examples/powertools-examples-parameters/README.md
  examples/powertools-examples-parameters/template.yaml
  examples/powertools-examples-serialization/README.md
  examples/powertools-examples-serialization/template.yaml
  examples/powertools-examples-sqs/README.md
  examples/powertools-examples-validation/README.md
Labels: size/L

#1303 fix: use default credentials provider for all provided SDK clients
  powertools-core/src/main/java/software/amazon/lambda/powertools/core/internal/LambdaConstants.java
  powertools-idempotency/src/main/java/software/amazon/lambda/powertools/idempotency/persistence/DynamoDBPersistenceStore.java
  powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/AppConfigProvider.java
  powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/DynamoDbProvider.java
  powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/SSMProvider.java
  powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/SecretsProvider.java
Labels: size/L

#1311 docs: Add discord + sec disclosure links to readme
  README.md
Labels: documentation, size/XS

#1307 chore: Make request for Logger explicitly for current class
  docs/core/logging.md
  examples/powertools-examples-parameters/src/main/java/org/demo/parameters/ParametersFunction.java
  powertools-idempotency/src/test/java/software/amazon/lambda/powertools/idempotency/handlers/IdempotencyFunction.java
Labels: size/S

#1318 docs: Adding external examples from AWS SAM CLI App Templates
  examples/README.md
Labels: size/S

#1293 docs: add support for docs versioning (#1239)
  .github/workflows/build-docs.yml
  .github/workflows/docs.yml
  .github/workflows/rebuild-latest-docs.yml
  .github/workflows/release-doc.yml
  .github/workflows/reusable-publish-docs.yml
  mkdocs.yml
Labels: size/L

#1322 docs: versioning - fix typo
  .github/workflows/rebuild-latest-docs.yml
Labels: size/XS

#1323 fix: Rollback doc changes
  .github/workflows/build-docs.yml
  .github/workflows/docs.yml
  .github/workflows/rebuild-latest-docs.yml
  .github/workflows/release-doc.yml
  .github/workflows/reusable-publish-docs.yml
  mkdocs.yml
Labels: size/L

#1326 docs: Add maintainers guide
  docs/processes/maintainers.md
  mkdocs.yml
Labels: size/L
