Repository aws-powertools/powertools-lambda-java, pull requests merged in 2023-08, with the labels that each got.

#1310 feat: large message in SQS and SNS
  .github/workflows/run-e2e-tests.yml
  docs/utilities/large_messages.md
  docs/utilities/sqs_large_message_handling.md
  mkdocs.yml
  pom.xml
  powertools-e2e-tests/handlers/idempotency/pom.xml
  powertools-e2e-tests/handlers/idempotency/src/main/java/software/amazon/lambda/powertools/e2e/Function.java
  powertools-e2e-tests/handlers/idempotency/src/main/resources/log4j2.xml
  powertools-e2e-tests/handlers/largemessage/pom.xml
  powertools-e2e-tests/handlers/largemessage/src/main/java/software/amazon/lambda/powertools/e2e/Function.java
  powertools-e2e-tests/handlers/largemessage/src/main/resources/log4j2.xml
  powertools-e2e-tests/handlers/largemessage_idempotent/pom.xml
  powertools-e2e-tests/handlers/largemessage_idempotent/src/main/java/software/amazon/lambda/powertools/e2e/Function.java
  powertools-e2e-tests/handlers/largemessage_idempotent/src/main/resources/log4j2.xml
  powertools-e2e-tests/handlers/pom.xml
  powertools-e2e-tests/pom.xml
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/IdempotencyE2ET.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/LargeMessageE2ET.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/LargeMessageIdempotentE2ET.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/LoggingE2ET.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/MetricsE2ET.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/ParametersE2ET.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/TracingE2ET.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/Infrastructure.java
  powertools-e2e-tests/src/test/resources/large_sqs_message.txt
  powertools-idempotency/pom.xml
  powertools-idempotency/src/main/java/software/amazon/lambda/powertools/idempotency/internal/IdempotentAspect.java
  powertools-large-messages/pom.xml
  powertools-large-messages/src/main/java/software/amazon/lambda/powertools/largemessages/LargeMessage.java
  powertools-large-messages/src/main/java/software/amazon/lambda/powertools/largemessages/LargeMessageConfig.java
  powertools-large-messages/src/main/java/software/amazon/lambda/powertools/largemessages/LargeMessageProcessingException.java
  powertools-large-messages/src/main/java/software/amazon/lambda/powertools/largemessages/internal/LargeMessageAspect.java
  powertools-large-messages/src/main/java/software/amazon/lambda/powertools/largemessages/internal/LargeMessageProcessor.java
  powertools-large-messages/src/main/java/software/amazon/lambda/powertools/largemessages/internal/LargeMessageProcessorFactory.java
  powertools-large-messages/src/main/java/software/amazon/lambda/powertools/largemessages/internal/LargeSNSMessageProcessor.java
  powertools-large-messages/src/main/java/software/amazon/lambda/powertools/largemessages/internal/LargeSQSMessageProcessor.java
  powertools-large-messages/src/test/java/software/amazon/lambda/powertools/largemessages/LargeMessageConfigTest.java
  powertools-large-messages/src/test/java/software/amazon/lambda/powertools/largemessages/internal/LargeMessageAspectTest.java
  powertools-large-messages/src/test/java/software/amazon/lambda/powertools/largemessages/internal/LargeMessageProcessorFactoryTest.java
  powertools-sqs/pom.xml
  powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/SqsLargeMessage.java
  powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/SqsUtils.java
  spotbugs-exclude.xml
Labels: size/XXL

#1306 chore: Add powertools specific user-agent-suffix to the AWS SDK v2 clients
  powertools-core/pom.xml
  powertools-core/src/main/java/software/amazon/lambda/powertools/core/internal/UserAgentConfigurator.java
  powertools-core/src/main/resources-filtered/version.properties
  powertools-core/src/test/java/software/amazon/lambda/powertools/core/internal/UserAgentConfiguratorTest.java
  powertools-core/src/test/resources/test.properties
  powertools-core/src/test/resources/unreadable.properties
  powertools-idempotency/src/main/java/software/amazon/lambda/powertools/idempotency/persistence/DynamoDBPersistenceStore.java
  powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/AppConfigProvider.java
  powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/BaseProvider.java
  powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/DynamoDbProvider.java
  powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/SSMProvider.java
  powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/SecretsProvider.java
  powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/SqsUtils.java
Labels: size/L

#1334 docs: improve contributing guide
  CONTRIBUTING.md
  docs/media/intellij_checkstyle_1.png
  docs/media/intellij_checkstyle_2.png
  docs/media/intellij_checkstyle_3.png
Labels: size/L

#1317 feat: Add Batch Processor module
  .sonarcloud.properties
  docs/utilities/batch.md
  docs/utilities/sqs_batch.md
  docs/utilities/sqs_large_message_handling.md
  examples/README.md
  examples/pom.xml
  examples/powertools-examples-batch/README.md
  examples/powertools-examples-batch/deploy/ddb-streams/template.yaml
  examples/powertools-examples-batch/deploy/kinesis/template.yml
  examples/powertools-examples-batch/deploy/sqs/template.yml
  examples/powertools-examples-batch/pom.xml
  examples/powertools-examples-batch/src/main/java/org/demo/batch/dynamo/DynamoDBStreamBatchHandler.java
  examples/powertools-examples-batch/src/main/java/org/demo/batch/dynamo/DynamoDBWriter.java
  examples/powertools-examples-batch/src/main/java/org/demo/batch/kinesis/KinesisBatchHandler.java
  examples/powertools-examples-batch/src/main/java/org/demo/batch/kinesis/KinesisBatchSender.java
  examples/powertools-examples-batch/src/main/java/org/demo/batch/model/DdbProduct.java
  examples/powertools-examples-batch/src/main/java/org/demo/batch/model/Product.java
  examples/powertools-examples-batch/src/main/java/org/demo/batch/sqs/SqsBatchHandler.java
  examples/powertools-examples-batch/src/main/java/org/demo/batch/sqs/SqsBatchSender.java
  examples/powertools-examples-batch/src/main/resources/log4j2.xml
  mkdocs.yml
  pom.xml
  powertools-batch/pom.xml
  powertools-batch/src/main/java/software/amazon/lambda/powertools/batch/BatchMessageHandlerBuilder.java
  powertools-batch/src/main/java/software/amazon/lambda/powertools/batch/builder/AbstractBatchMessageHandlerBuilder.java
  powertools-batch/src/main/java/software/amazon/lambda/powertools/batch/builder/DynamoDbBatchMessageHandlerBuilder.java
  powertools-batch/src/main/java/software/amazon/lambda/powertools/batch/builder/KinesisBatchMessageHandlerBuilder.java
  powertools-batch/src/main/java/software/amazon/lambda/powertools/batch/builder/SqsBatchMessageHandlerBuilder.java
  powertools-batch/src/main/java/software/amazon/lambda/powertools/batch/exception/DeserializationNotSupportedException.java
  powertools-batch/src/main/java/software/amazon/lambda/powertools/batch/handler/BatchMessageHandler.java
  powertools-batch/src/main/java/software/amazon/lambda/powertools/batch/handler/DynamoDbBatchMessageHandler.java
  powertools-batch/src/main/java/software/amazon/lambda/powertools/batch/handler/KinesisStreamsBatchMessageHandler.java
  powertools-batch/src/main/java/software/amazon/lambda/powertools/batch/handler/SqsBatchMessageHandler.java
  powertools-batch/src/test/java/software/amazon/lambda/powertools/batch/DdbBatchProcessorTest.java
  powertools-batch/src/test/java/software/amazon/lambda/powertools/batch/KinesisBatchProcessorTest.java
  powertools-batch/src/test/java/software/amazon/lambda/powertools/batch/SQSBatchProcessorTest.java
  powertools-batch/src/test/java/software/amazon/lambda/powertools/batch/model/Basket.java
  powertools-batch/src/test/java/software/amazon/lambda/powertools/batch/model/Product.java
  powertools-batch/src/test/resources/dynamo_event.json
  powertools-batch/src/test/resources/kinesis_event.json
  powertools-batch/src/test/resources/sqs_event.json
  powertools-batch/src/test/resources/sqs_fifo_event.json
  powertools-e2e-tests/handlers/batch/pom.xml
  powertools-e2e-tests/handlers/batch/src/main/java/software/amazon/lambda/powertools/e2e/Function.java
  powertools-e2e-tests/handlers/batch/src/main/java/software/amazon/lambda/powertools/e2e/model/Product.java
  powertools-e2e-tests/handlers/batch/src/main/resources/log4j2.xml
  powertools-e2e-tests/handlers/pom.xml
  powertools-e2e-tests/pom.xml
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/BatchE2ET.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/Infrastructure.java
  powertools-serialization/src/main/java/software/amazon/lambda/powertools/utilities/EventDeserializer.java
  powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/SqsBatch.java
  powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/SqsUtils.java
Labels: size/XXL

#1339 chore: apply checkstyle again
  .sonarcloud.properties
  examples/powertools-examples-cloudformation/src/main/java/helloworld/App.java
  examples/powertools-examples-core/src/main/java/helloworld/App.java
  examples/powertools-examples-sqs/src/main/java/org/demo/sqs/SqsMessageSender.java
  powertools-cloudformation/src/test/java/software/amazon/lambda/powertools/cloudformation/CloudFormationResponseTest.java
  powertools-core/src/test/java/software/amazon/lambda/powertools/core/internal/UserAgentConfiguratorTest.java
  powertools-e2e-tests/handlers/largemessage/src/main/java/software/amazon/lambda/powertools/e2e/Function.java
  powertools-e2e-tests/handlers/largemessage_idempotent/src/main/java/software/amazon/lambda/powertools/e2e/Function.java
  powertools-e2e-tests/handlers/tracing/src/main/java/software/amazon/lambda/powertools/e2e/Function.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/LargeMessageE2ET.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/LargeMessageIdempotentE2ET.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/Infrastructure.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/metrics/MetricsFetcher.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/tracing/TraceFetcher.java
  powertools-idempotency/src/main/java/software/amazon/lambda/powertools/idempotency/persistence/DynamoDBPersistenceStore.java
  powertools-large-messages/src/main/java/software/amazon/lambda/powertools/largemessages/LargeMessage.java
  powertools-large-messages/src/main/java/software/amazon/lambda/powertools/largemessages/internal/LargeMessageAspect.java
  powertools-large-messages/src/main/java/software/amazon/lambda/powertools/largemessages/internal/LargeMessageProcessor.java
  powertools-large-messages/src/main/java/software/amazon/lambda/powertools/largemessages/internal/LargeSQSMessageProcessor.java
  powertools-large-messages/src/test/java/software/amazon/lambda/powertools/largemessages/internal/LargeMessageAspectTest.java
  powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/LambdaJsonLayout.java
  powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/PowertoolsResolver.java
  powertools-logging/src/test/java/org/apache/logging/log4j/core/layout/LambdaJsonLayoutTest.java
  powertools-metrics/src/main/java/software/amazon/lambda/powertools/metrics/MetricsUtils.java
  powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/MetricsLoggerTest.java
  powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/handlers/PowertoolsMetricsEnabledDefaultDimensionHandler.java
  powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/handlers/PowertoolsMetricsEnabledDefaultNoDimensionHandler.java
  powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/internal/LambdaMetricsAspectTest.java
  powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/AppConfigProvider.java
  powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/BaseProvider.java
  powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/DynamoDbProvider.java
  powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/SSMProvider.java
  powertools-parameters/src/main/java/software/amazon/lambda/powertools/parameters/SecretsProvider.java
  powertools-parameters/src/test/java/software/amazon/lambda/powertools/parameters/DynamoDbProviderTest.java
  powertools-parameters/src/test/java/software/amazon/lambda/powertools/parameters/SSMProviderTest.java
  powertools-parameters/src/test/java/software/amazon/lambda/powertools/parameters/internal/LambdaParametersAspectTest.java
  powertools-serialization/src/main/java/software/amazon/lambda/powertools/utilities/EventDeserializer.java
  powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/SqsUtils.java
  powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/internal/BatchContext.java
  powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/internal/SqsLargeMessageAspect.java
  powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/SqsUtilsBatchProcessorTest.java
  powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/SqsUtilsFifoBatchProcessorTest.java
  powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/SqsUtilsLargeMessageTest.java
  powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/internal/SqsLargeMessageAspectTest.java
  powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/internal/SqsMessageBatchProcessorAspectTest.java
  powertools-test-suite/src/test/java/software/amazon/lambda/powertools/testsuite/LoggingOrderTest.java
  powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/TracingUtilsTest.java
  powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/internal/LambdaTracingAspectTest.java
  powertools-validation/src/test/java/software/amazon/lambda/powertools/validation/ValidationUtilsTest.java
  powertools-validation/src/test/java/software/amazon/lambda/powertools/validation/internal/ValidationAspectTest.java
Labels: size/XXL

#1341 chore: Add 'v2' branch to build workflows
  .github/workflows/build-docs.yml
  .github/workflows/build.yml
  .github/workflows/run-e2e-tests.yml
  .github/workflows/spotbugs.yml
Labels: size/XS, maintenance

#1346 chore: Start V2 branch
  README.md
  docs/utilities/large_messages.md
  docs/utilities/sqs_batch.md
  docs/utilities/sqs_large_message_handling.md
  examples/pom.xml
  examples/powertools-examples-sqs/README.md
  examples/powertools-examples-sqs/events/event.json
  examples/powertools-examples-sqs/pom.xml
  examples/powertools-examples-sqs/src/main/java/org/demo/sqs/SqsMessageSender.java
  examples/powertools-examples-sqs/src/main/java/org/demo/sqs/SqsPoller.java
  examples/powertools-examples-sqs/src/main/resources/log4j2.xml
  examples/powertools-examples-sqs/template.yaml
  mkdocs.yml
  pom.xml
  powertools-sqs/pom.xml
  powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/SQSBatchProcessingException.java
  powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/SqsBatch.java
  powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/SqsLargeMessage.java
  powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/SqsMessageHandler.java
  powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/SqsUtils.java
  powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/exception/SkippedMessageDueToFailedBatchException.java
  powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/internal/BatchContext.java
  powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/internal/SqsLargeMessageAspect.java
  powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/internal/SqsMessageBatchProcessorAspect.java
  powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/SampleSqsHandler.java
  powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/SqsUtilsBatchProcessorTest.java
  powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/SqsUtilsFifoBatchProcessorTest.java
  powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/SqsUtilsLargeMessageTest.java
  powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/handlers/LambdaHandlerApiGateway.java
  powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/handlers/PartialBatchFailureSuppressedHandler.java
  powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/handlers/PartialBatchPartialFailureHandler.java
  powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/handlers/PartialBatchSuccessHandler.java
  powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/handlers/SqsMessageHandler.java
  powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/handlers/SqsMessageHandlerWithNonRetryableHandler.java
  powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/handlers/SqsMessageHandlerWithNonRetryableHandlerWithDelete.java
  powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/handlers/SqsNoDeleteMessageHandler.java
  powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/internal/SqsLargeMessageAspectTest.java
  powertools-sqs/src/test/java/software/amazon/lambda/powertools/sqs/internal/SqsMessageBatchProcessorAspectTest.java
  powertools-sqs/src/test/resources/SqsFifoBatchEvent.json
  powertools-sqs/src/test/resources/sampleSqsBatchEvent.json
  powertools-sqs/src/test/resources/sampleSqsBatchEventBatchSize25.json
  powertools-sqs/src/test/resources/threeMessageSqsBatchEvent.json
  powertools-test-suite/pom.xml
  powertools-test-suite/src/test/java/software/amazon/lambda/powertools/testsuite/LoggingOrderTest.java
  powertools-test-suite/src/test/java/software/amazon/lambda/powertools/testsuite/handler/LoggingOrderMessageHandler.java
  powertools-test-suite/src/test/java/software/amazon/lambda/powertools/testsuite/handler/TracingLoggingStreamMessageHandler.java
  powertools-test-suite/src/test/resources/log4j2.xml
Labels: size/XXL

#1348 chore: v2 - fix version
  examples/pom.xml
  examples/powertools-examples-batch/pom.xml
  examples/powertools-examples-cloudformation/pom.xml
  examples/powertools-examples-core/pom.xml
  examples/powertools-examples-idempotency/pom.xml
  examples/powertools-examples-parameters/pom.xml
  examples/powertools-examples-serialization/pom.xml
  examples/powertools-examples-validation/pom.xml
  pom.xml
  powertools-batch/pom.xml
  powertools-cloudformation/pom.xml
  powertools-core/pom.xml
  powertools-e2e-tests/handlers/pom.xml
  powertools-e2e-tests/pom.xml
  powertools-idempotency/pom.xml
  powertools-large-messages/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-serialization/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
Labels: size/M

#1321 docs: Adding CDK example
  examples/.gitignore
  examples/README.md
  examples/pom.xml
  examples/powertools-examples-core/.gitignore
  examples/powertools-examples-core/README.md
  examples/powertools-examples-core/cdk/README.md
  examples/powertools-examples-core/cdk/app/events/event.json
  examples/powertools-examples-core/cdk/app/pom.xml
  examples/powertools-examples-core/cdk/app/src/main/java/helloworld/App.java
  examples/powertools-examples-core/cdk/app/src/main/java/helloworld/AppStream.java
  examples/powertools-examples-core/cdk/app/src/main/resources/log4j2.xml
  examples/powertools-examples-core/cdk/app/src/test/java/helloworld/AppTest.java
  examples/powertools-examples-core/cdk/infra/cdk.json
  examples/powertools-examples-core/cdk/infra/pom.xml
  examples/powertools-examples-core/cdk/infra/src/main/java/cdk/CdkApp.java
  examples/powertools-examples-core/cdk/infra/src/main/java/cdk/CdkStack.java
  examples/powertools-examples-core/cdk/infra/src/test/java/cdk/CdkStackTest.java
  examples/powertools-examples-core/sam/README.md
  examples/powertools-examples-core/sam/events/event.json
  examples/powertools-examples-core/sam/pom.xml
  examples/powertools-examples-core/sam/src/main/java/helloworld/App.java
  examples/powertools-examples-core/sam/src/main/java/helloworld/AppStream.java
  examples/powertools-examples-core/sam/src/main/resources/log4j2.xml
  examples/powertools-examples-core/sam/src/test/java/helloworld/AppTest.java
  examples/powertools-examples-core/sam/template.yaml
  examples/powertools-examples-idempotency/src/main/java/helloworld/App.java
Labels: size/XL

#1376 fix: Roll log4j shade transformer forwards
  examples/powertools-examples-batch/pom.xml
  examples/powertools-examples-cloudformation/pom.xml
  examples/powertools-examples-core/cdk/app/pom.xml
  examples/powertools-examples-core/sam/pom.xml
  examples/powertools-examples-idempotency/pom.xml
  examples/powertools-examples-sqs/pom.xml
  powertools-e2e-tests/handlers/pom.xml
Labels: size/M

#1381 chore:Prep release 1.17.0
  CHANGELOG.md
  examples/pom.xml
  examples/powertools-examples-batch/pom.xml
  examples/powertools-examples-cloudformation/pom.xml
  examples/powertools-examples-core/cdk/infra/pom.xml
  examples/powertools-examples-core/sam/pom.xml
  examples/powertools-examples-idempotency/pom.xml
  examples/powertools-examples-parameters/pom.xml
  examples/powertools-examples-serialization/pom.xml
  examples/powertools-examples-sqs/pom.xml
  examples/powertools-examples-validation/pom.xml
  pom.xml
  powertools-batch/pom.xml
  powertools-cloudformation/pom.xml
  powertools-core/pom.xml
  powertools-e2e-tests/handlers/pom.xml
  powertools-e2e-tests/pom.xml
  powertools-idempotency/pom.xml
  powertools-large-messages/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-serialization/pom.xml
  powertools-sqs/pom.xml
  powertools-test-suite/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
Labels: size/M

#1382 chore: Fix missing version change pieces
  README.md
  mkdocs.yml
Labels: size/XS

#1383 fix: Don't deploy the CDK
  examples/powertools-examples-core/cdk/infra/pom.xml
Labels: size/XS

#1385 chore: Clean up batch POM
  powertools-batch/pom.xml
Labels: size/XS

#1374 docs: Change link to absolute versioned path for examples
  README.md
Labels: size/XS

#1232 chore: secure github actions using hash instead of versions
  .github/workflows/auto-merge.yml
  .github/workflows/build-docs.yml
  .github/workflows/build.yml
  .github/workflows/dispatch_analytics.yml
  .github/workflows/docs.yml
  .github/workflows/publish.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release-prep.yml
  .github/workflows/run-e2e-tests.yml
  .github/workflows/secure_workflows.yml
  .github/workflows/spotbugs.yml
Labels: size/M

#1359 docs: Update gradle configuration readme
  .github/workflows/build.yml
  .gitignore
  README.md
  docs/index.md
  examples/powertools-examples-core/README.md
  examples/powertools-examples-core/gradle/README.md
  examples/powertools-examples-core/gradle/build.gradle
  examples/powertools-examples-core/gradle/events/event.json
  examples/powertools-examples-core/gradle/gradle/wrapper/.gitignore
  examples/powertools-examples-core/gradle/gradle/wrapper/gradle-wrapper.jar
  examples/powertools-examples-core/gradle/gradle/wrapper/gradle-wrapper.properties
  examples/powertools-examples-core/gradle/gradlew
  examples/powertools-examples-core/gradle/gradlew.bat
  examples/powertools-examples-core/gradle/src/main/java/helloworld/App.java
  examples/powertools-examples-core/gradle/src/main/java/helloworld/AppStream.java
  examples/powertools-examples-core/gradle/src/test/java/helloworld/AppTest.java
  examples/powertools-examples-core/gradle/template.yaml
Labels: size/XL

#1388 chore: skip deployment in tests and examples
  examples/pom.xml
  examples/powertools-examples-batch/pom.xml
  examples/powertools-examples-cloudformation/pom.xml
  examples/powertools-examples-core/cdk/app/pom.xml
  examples/powertools-examples-core/cdk/infra/pom.xml
  examples/powertools-examples-core/sam/pom.xml
  examples/powertools-examples-idempotency/pom.xml
  examples/powertools-examples-parameters/pom.xml
  examples/powertools-examples-serialization/pom.xml
  examples/powertools-examples-sqs/pom.xml
  examples/powertools-examples-validation/pom.xml
  powertools-e2e-tests/pom.xml
  powertools-test-suite/pom.xml
Labels: size/XL

#1409 chore: update v2
  .github/workflows/auto-merge.yml
  .github/workflows/build-docs.yml
  .github/workflows/build.yml
  .github/workflows/dispatch_analytics.yml
  .github/workflows/docs.yml
  .github/workflows/publish.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release-prep.yml
  .github/workflows/run-e2e-tests.yml
  .github/workflows/secure_workflows.yml
  .github/workflows/spotbugs.yml
  .gitignore
  README.md
  docs/index.md
  examples/pom.xml
  examples/powertools-examples-batch/pom.xml
  examples/powertools-examples-cloudformation/pom.xml
  examples/powertools-examples-core-utilities/README.md
  examples/powertools-examples-core-utilities/cdk/app/pom.xml
  examples/powertools-examples-core-utilities/cdk/infra/pom.xml
  examples/powertools-examples-core-utilities/gradle/README.md
  examples/powertools-examples-core-utilities/gradle/build.gradle
  examples/powertools-examples-core-utilities/gradle/events/event.json
  examples/powertools-examples-core-utilities/gradle/gradle/wrapper/.gitignore
  examples/powertools-examples-core-utilities/gradle/gradle/wrapper/gradle-wrapper.jar
  examples/powertools-examples-core-utilities/gradle/gradle/wrapper/gradle-wrapper.properties
  examples/powertools-examples-core-utilities/gradle/gradlew
  examples/powertools-examples-core-utilities/gradle/gradlew.bat
  examples/powertools-examples-core-utilities/gradle/src/main/java/helloworld/App.java
  examples/powertools-examples-core-utilities/gradle/src/main/java/helloworld/AppStream.java
  examples/powertools-examples-core-utilities/gradle/src/test/java/helloworld/AppTest.java
  examples/powertools-examples-core-utilities/gradle/template.yaml
  examples/powertools-examples-core-utilities/sam/pom.xml
  examples/powertools-examples-idempotency/pom.xml
  examples/powertools-examples-parameters/pom.xml
  examples/powertools-examples-serialization/pom.xml
  examples/powertools-examples-validation/pom.xml
  pom.xml
  powertools-e2e-tests/pom.xml
Labels: size/XXL
