Repository aws-powertools/powertools-lambda-java, pull requests merged in 2023-09, with the labels that each got.

#1408 chore: remove aspectj-rt from the library
  examples/powertools-examples-batch/pom.xml
  examples/powertools-examples-cloudformation/pom.xml
  examples/powertools-examples-core-utilities/cdk/app/pom.xml
  examples/powertools-examples-core-utilities/sam/pom.xml
  examples/powertools-examples-idempotency/pom.xml
  examples/powertools-examples-parameters/pom.xml
  examples/powertools-examples-serialization/pom.xml
  examples/powertools-examples-validation/pom.xml
  powertools-cloudformation/pom.xml
  powertools-common/pom.xml
  powertools-e2e-tests/handlers/idempotency/pom.xml
  powertools-e2e-tests/handlers/largemessage/pom.xml
  powertools-e2e-tests/handlers/largemessage_idempotent/pom.xml
  powertools-e2e-tests/handlers/logging/pom.xml
  powertools-e2e-tests/handlers/metrics/pom.xml
  powertools-e2e-tests/handlers/parameters/pom.xml
  powertools-e2e-tests/handlers/pom.xml
  powertools-e2e-tests/handlers/tracing/pom.xml
  powertools-idempotency/pom.xml
  powertools-large-messages/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
Labels: size/XXL

#1411 docs(logging): correct log example keys
  docs/core/logging.md
Labels: size/XS

#1420 fix: array jmespath fail in idempotency module
  powertools-idempotency/src/main/java/software/amazon/lambda/powertools/idempotency/persistence/BasePersistenceStore.java
  powertools-idempotency/src/test/java/software/amazon/lambda/powertools/idempotency/internal/IdempotencyAspectTest.java
Labels: bug, size/M, priority:2

#1196 chore: Reporting size of the jars in GitHub comments
  .github/workflows/pr_artifacts_size.yml
  .github/workflows/pr_build.yml
  pom.xml
Labels: size/M

#1363 docs: Add Serveless Framework example
  examples/README.md
  examples/pom.xml
  examples/powertools-examples-core/README.md
  examples/powertools-examples-core/serverless/README.md
  examples/powertools-examples-core/serverless/pom.xml
  examples/powertools-examples-core/serverless/serverless.yml
  examples/powertools-examples-core/serverless/src/main/java/helloworld/App.java
  examples/powertools-examples-core/serverless/src/main/java/helloworld/AppStream.java
  examples/powertools-examples-core/serverless/src/main/resources/log4j2.xml
  examples/powertools-examples-core/serverless/src/test/java/helloworld/AppTest.java
Labels: size/L
