Repository aws-powertools/powertools-lambda-java, pull requests merged in 2023-12, with the labels that each got.

#1489 feat(v2): Validation failures return 400s
  docs/utilities/validation.md
  powertools-e2e-tests/handlers/pom.xml
  powertools-e2e-tests/handlers/validation-alb-event/pom.xml
  powertools-e2e-tests/handlers/validation-alb-event/src/main/java/software/amazon/lambda/powertools/e2e/Function.java
  powertools-e2e-tests/handlers/validation-alb-event/src/main/resources/log4j2.xml
  powertools-e2e-tests/handlers/validation-alb-event/src/main/resources/validation/inbound_schema.json
  powertools-e2e-tests/handlers/validation-alb-event/src/main/resources/validation/outbound_schema.json
  powertools-e2e-tests/handlers/validation-apigw-event/pom.xml
  powertools-e2e-tests/handlers/validation-apigw-event/src/main/java/software/amazon/lambda/powertools/e2e/Function.java
  powertools-e2e-tests/handlers/validation-apigw-event/src/main/resources/log4j2.xml
  powertools-e2e-tests/handlers/validation-apigw-event/src/main/resources/validation/inbound_schema.json
  powertools-e2e-tests/handlers/validation-apigw-event/src/main/resources/validation/outbound_schema.json
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/ValidationALBE2ET.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/ValidationApiGWE2ET.java
  powertools-e2e-tests/src/test/resources/validation/invalid_alb_in_event.json
  powertools-e2e-tests/src/test/resources/validation/invalid_alb_out_event.json
  powertools-e2e-tests/src/test/resources/validation/invalid_api_gw_in_event.json
  powertools-e2e-tests/src/test/resources/validation/invalid_api_gw_out_event.json
  powertools-e2e-tests/src/test/resources/validation/valid_alb_in_out_event.json
  powertools-e2e-tests/src/test/resources/validation/valid_api_gw_in_out_event.json
  powertools-validation/src/main/java/software/amazon/lambda/powertools/validation/internal/ValidationAspect.java
  powertools-validation/src/test/java/software/amazon/lambda/powertools/validation/handlers/GenericSchemaV7APIGatewayProxyRequestEventHandler.java
  powertools-validation/src/test/java/software/amazon/lambda/powertools/validation/handlers/GenericSchemaV7StringHandler.java
  powertools-validation/src/test/java/software/amazon/lambda/powertools/validation/handlers/ValidationInboundAPIGatewayV2HTTPEventHandler.java
  powertools-validation/src/test/java/software/amazon/lambda/powertools/validation/internal/HandledResponseEventsArgumentsProvider.java
  powertools-validation/src/test/java/software/amazon/lambda/powertools/validation/internal/ResponseEventsArgumentsProvider.java
  powertools-validation/src/test/java/software/amazon/lambda/powertools/validation/internal/ValidationAspectTest.java
Labels: size/XXL

#1534 chore: fix end 2 end build
  .github/workflows/pr_artifacts_size.yml
  .github/workflows/run-e2e-tests.yml
Labels: size/S

#1532 docs: HelloWorldStreamFunction in examples fails with sam
  examples/powertools-examples-core/sam/src/main/java/helloworld/AppStream.java
Labels: size/S

#1536 build(deps): bump aspectj to 1.9.21 for jdk21
  docs/index.md
  powertools-e2e-tests/handlers/pom.xml
Labels: size/XS

#1533 chore: SAM and Terraform IaC extracted from pr_build and simplified approach.
  .github/workflows/pr_build.yml
  .github/workflows/pr_iac_lint.yml
Labels: size/M

#1535 chore: cleanup poms and reduce warning noise
  examples/pom.xml
  examples/powertools-examples-batch/pom.xml
  examples/powertools-examples-cloudformation/pom.xml
  examples/powertools-examples-core-utilities/cdk/app/pom.xml
  examples/powertools-examples-core-utilities/cdk/infra/pom.xml
  examples/powertools-examples-core-utilities/terraform/pom.xml
  examples/powertools-examples-idempotency/pom.xml
  examples/powertools-examples-parameters/pom.xml
  examples/powertools-examples-serialization/pom.xml
  examples/powertools-examples-validation/pom.xml
  pom.xml
  powertools-cloudformation/pom.xml
  powertools-common/pom.xml
  powertools-e2e-tests/pom.xml
  powertools-idempotency/pom.xml
  powertools-large-messages/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-serialization/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
  powertools-validation/src/main/java/software/amazon/lambda/powertools/validation/internal/ValidationAspect.java
Labels: size/L

#1537 chore: Support spotbugs running anywhere
  .mvn/README
  checkstyle.xml
  examples/spotbugs-exclude.xml
  pom.xml
  powertools-logging/spotbugs-exclude.xml
  powertools-parameters/spotbugs-exclude.xml
  spotbugs-exclude.xml
Labels: size/L, v2
