Repository aws-powertools/powertools-lambda-java, pull requests merged in 2023-10, with the labels that each got.

#1453 docs: apply line highlight only for default light mode
  docs/stylesheets/extra.css
Labels: size/XS

#1456 fix: Fix schema validation unit test build issues
  powertools-validation/src/test/java/software/amazon/lambda/powertools/validation/ValidationUtilsTest.java
Labels: size/S

#1457 fix: json schema 403 error
  powertools-validation/src/main/java/software/amazon/lambda/powertools/validation/ValidationConfig.java
  powertools-validation/src/main/java/software/amazon/lambda/powertools/validation/ValidationUtils.java
  powertools-validation/src/main/resources/schemas/meta/applicator
  powertools-validation/src/main/resources/schemas/meta/content
  powertools-validation/src/main/resources/schemas/meta/core
  powertools-validation/src/main/resources/schemas/meta/format
  powertools-validation/src/main/resources/schemas/meta/meta-data
  powertools-validation/src/main/resources/schemas/meta/validation
  powertools-validation/src/main/resources/schemas/meta_schema_V201909
  powertools-validation/src/main/resources/schemas/meta_schema_V4
  powertools-validation/src/main/resources/schemas/meta_schema_V6
  powertools-validation/src/main/resources/schemas/meta_schema_V7
  powertools-validation/src/test/java/software/amazon/lambda/powertools/validation/ValidationUtilsTest.java
Labels: size/XL

#1478 feat: Terraform example
  .github/workflows/pr_build.yml
  .gitignore
  examples/pom.xml
  examples/powertools-examples-core/README.md
  examples/powertools-examples-core/terraform/.tflint.hcl
  examples/powertools-examples-core/terraform/README.md
  examples/powertools-examples-core/terraform/infra/api-gateway.tf
  examples/powertools-examples-core/terraform/infra/lambda.tf
  examples/powertools-examples-core/terraform/main.tf
  examples/powertools-examples-core/terraform/pom.xml
  examples/powertools-examples-core/terraform/src/main/java/helloworld/App.java
  examples/powertools-examples-core/terraform/src/main/java/helloworld/AppStream.java
  examples/powertools-examples-core/terraform/src/main/resources/log4j2.xml
  examples/powertools-examples-core/terraform/src/test/java/helloworld/AppTest.java
Labels: size/XL

#1454 docs: Adding Kotlin example.
  .github/workflows/pr_build.yml
  examples/README.md
  examples/powertools-examples-core/README.md
  examples/powertools-examples-core/cdk/README.md
  examples/powertools-examples-core/gradle/gradlew.bat
  examples/powertools-examples-core/kotlin/README.md
  examples/powertools-examples-core/kotlin/build.gradle.kts
  examples/powertools-examples-core/kotlin/events/event.json
  examples/powertools-examples-core/kotlin/gradle/wrapper/.gitignore
  examples/powertools-examples-core/kotlin/gradle/wrapper/gradle-wrapper.jar
  examples/powertools-examples-core/kotlin/gradle/wrapper/gradle-wrapper.properties
  examples/powertools-examples-core/kotlin/gradlew
  examples/powertools-examples-core/kotlin/gradlew.bat
  examples/powertools-examples-core/kotlin/src/main/kotlin/helloworld/App.kt
  examples/powertools-examples-core/kotlin/src/main/kotlin/helloworld/AppStream.kt
  examples/powertools-examples-core/kotlin/src/test/kotlin/helloworld/AppTest.kt
  examples/powertools-examples-core/kotlin/template.yaml
  examples/powertools-examples-core/serverless/README.md
Labels: size/XL

#1488 chore: java21 support in our build
  .github/workflows/pr_build.yml
  examples/powertools-examples-batch/pom.xml
  examples/powertools-examples-cloudformation/pom.xml
  examples/powertools-examples-core/cdk/app/pom.xml
  examples/powertools-examples-core/cdk/app/src/test/java/helloworld/AppTest.java
  examples/powertools-examples-core/gradle/build.gradle
  examples/powertools-examples-core/gradle/src/test/java/helloworld/AppTest.java
  examples/powertools-examples-core/sam/pom.xml
  examples/powertools-examples-core/sam/src/test/java/helloworld/AppTest.java
  examples/powertools-examples-core/serverless/pom.xml
  examples/powertools-examples-core/serverless/src/test/java/helloworld/AppTest.java
  examples/powertools-examples-core/terraform/pom.xml
  examples/powertools-examples-core/terraform/src/test/java/helloworld/AppTest.java
  examples/powertools-examples-idempotency/pom.xml
  examples/powertools-examples-idempotency/src/test/java/helloworld/AppTest.java
  examples/powertools-examples-idempotency/src/test/resources/event.json
  examples/powertools-examples-parameters/pom.xml
  examples/powertools-examples-serialization/pom.xml
  examples/powertools-examples-serialization/src/test/java/org/demo/serialization/APIGatewayRequestDeserializationFunctionTest.java
  examples/powertools-examples-serialization/src/test/java/org/demo/serialization/SQSEventDeserializationFunctionTest.java
  examples/powertools-examples-sqs/pom.xml
  examples/powertools-examples-validation/pom.xml
  examples/powertools-examples-validation/src/test/java/org/demo/validation/InboundValidationTest.java
  pom.xml
  powertools-batch/pom.xml
  powertools-cloudformation/pom.xml
  powertools-core/pom.xml
  powertools-idempotency/pom.xml
  powertools-large-messages/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-sqs/pom.xml
  powertools-test-suite/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
Labels: size/XL

#1487 chore: add missing projects and improve workflow
  .github/workflows/pr_build.yml
  .github/workflows/run-e2e-tests.yml
Labels: size/M

#1486 docs(customer-reference): add Vertex Pharmaceuticals as a customer reference
  README.md
Labels: size/XS

#1472 fix: enforce jackson databind version
  powertools-serialization/pom.xml
Labels: size/XS

#1492 chore(v2): Merge main
  .github/dependabot.yml
  .github/workflows/pr_build.yml
  .github/workflows/run-e2e-tests.yml
  .gitignore
  examples/README.md
  examples/pom.xml
  examples/powertools-examples-batch/pom.xml
  examples/powertools-examples-cloudformation/pom.xml
  examples/powertools-examples-core-utilities/README.md
  examples/powertools-examples-core-utilities/cdk/README.md
  examples/powertools-examples-core-utilities/cdk/app/pom.xml
  examples/powertools-examples-core-utilities/cdk/app/src/test/java/helloworld/AppTest.java
  examples/powertools-examples-core-utilities/gradle/build.gradle
  examples/powertools-examples-core-utilities/gradle/src/test/java/helloworld/AppTest.java
  examples/powertools-examples-core-utilities/kotlin/README.md
  examples/powertools-examples-core-utilities/kotlin/build.gradle.kts
  examples/powertools-examples-core-utilities/kotlin/events/event.json
  examples/powertools-examples-core-utilities/kotlin/gradle/wrapper/.gitignore
  examples/powertools-examples-core-utilities/kotlin/gradle/wrapper/gradle-wrapper.jar
  examples/powertools-examples-core-utilities/kotlin/gradle/wrapper/gradle-wrapper.properties
  examples/powertools-examples-core-utilities/kotlin/gradlew
  examples/powertools-examples-core-utilities/kotlin/gradlew.bat
  examples/powertools-examples-core-utilities/kotlin/src/main/kotlin/helloworld/App.kt
  examples/powertools-examples-core-utilities/kotlin/src/main/kotlin/helloworld/AppStream.kt
  examples/powertools-examples-core-utilities/kotlin/src/test/kotlin/helloworld/AppTest.kt
  examples/powertools-examples-core-utilities/kotlin/template.yaml
  examples/powertools-examples-core-utilities/sam/src/test/java/helloworld/AppTest.java
  examples/powertools-examples-core-utilities/serverless/README.md
  examples/powertools-examples-core-utilities/serverless/pom.xml
  examples/powertools-examples-core-utilities/serverless/src/test/java/helloworld/AppTest.java
  examples/powertools-examples-core-utilities/terraform/.tflint.hcl
  examples/powertools-examples-core-utilities/terraform/README.md
  examples/powertools-examples-core-utilities/terraform/infra/api-gateway.tf
  examples/powertools-examples-core-utilities/terraform/infra/lambda.tf
  examples/powertools-examples-core-utilities/terraform/main.tf
  examples/powertools-examples-core-utilities/terraform/pom.xml
  examples/powertools-examples-core-utilities/terraform/src/main/java/helloworld/App.java
  examples/powertools-examples-core-utilities/terraform/src/main/java/helloworld/AppStream.java
  examples/powertools-examples-core-utilities/terraform/src/main/resources/log4j2.xml
  examples/powertools-examples-idempotency/pom.xml
  examples/powertools-examples-idempotency/src/test/java/helloworld/AppTest.java
  examples/powertools-examples-idempotency/src/test/resources/event.json
  examples/powertools-examples-serialization/pom.xml
  examples/powertools-examples-serialization/src/test/java/org/demo/serialization/APIGatewayRequestDeserializationFunctionTest.java
  examples/powertools-examples-serialization/src/test/java/org/demo/serialization/SQSEventDeserializationFunctionTest.java
  examples/powertools-examples-validation/pom.xml
  examples/powertools-examples-validation/src/test/java/org/demo/validation/InboundValidationTest.java
  pom.xml
  powertools-batch/pom.xml
  powertools-cloudformation/pom.xml
  powertools-common/pom.xml
  powertools-e2e-tests/pom.xml
  powertools-idempotency/pom.xml
  powertools-large-messages/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
Labels: size/XXL

#1493 chore: artifacts size on good branches
  .github/workflows/pr_artifacts_size.yml
  examples/powertools-examples-idempotency/pom.xml
  powertools-idempotency/pom.xml
Labels: size/M

#1494 chore: merge main into v2
  .github/workflows/pr_artifacts_size.yml
  README.md
  examples/powertools-examples-idempotency/pom.xml
  powertools-idempotency/pom.xml
  powertools-serialization/pom.xml
Labels: size/M

#1495 chore(v2): clean examples
  examples/powertools-examples-core-utilities/cdk/app/pom.xml
  examples/powertools-examples-core-utilities/sam/pom.xml
  examples/powertools-examples-core-utilities/serverless/pom.xml
  examples/powertools-examples-core-utilities/terraform/pom.xml
Labels: size/L
