Repository aws-powertools/powertools-lambda-java, pull requests merged in 2023-02, with the labels that each got.

#1032 Bump Mockito to latest compatible version.
  .github/dependabot.yml
  pom.xml
Labels: size/XS

#1000 feat(metrics): introduce MetricsUtils.withMetricsLogger utility
  docs/core/metrics.md
  powertools-metrics/src/main/java/software/amazon/lambda/powertools/metrics/MetricsUtils.java
  powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/MetricsLoggerTest.java
Labels: size/M

#1052 chore: update the project version to 1.14.0
  CHANGELOG.md
  README.md
  mkdocs.yml
  pom.xml
  powertools-cloudformation/pom.xml
  powertools-core/pom.xml
  powertools-idempotency/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-serialization/pom.xml
  powertools-sqs/pom.xml
  powertools-test-suite/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
Labels: size/M

#1062 chore(governance): update issue templates
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation-improvements.md
  .github/ISSUE_TEMPLATE/documentation_improvements.yml
  .github/ISSUE_TEMPLATE/maintenance.yml
  .github/ISSUE_TEMPLATE/share_your_work.yml
Labels: size/L

#1051 [feat] Import examples from aws-samples/aws-lambda-powertools-examples
  .github/workflows/build.yml
  README.md
  examples/.gitignore
  examples/README.md
  examples/pom.xml
  examples/powertools-examples-core/.gitignore
  examples/powertools-examples-core/README.md
  examples/powertools-examples-core/events/event.json
  examples/powertools-examples-core/pom.xml
  examples/powertools-examples-core/src/main/java/helloworld/App.java
  examples/powertools-examples-core/src/main/java/helloworld/AppStream.java
  examples/powertools-examples-core/src/main/resources/log4j2.xml
  examples/powertools-examples-core/src/test/java/helloworld/AppTest.java
  examples/powertools-examples-core/template.yaml
  examples/powertools-examples-idempotency/README.md
  examples/powertools-examples-idempotency/pom.xml
  examples/powertools-examples-idempotency/src/main/java/helloworld/App.java
  examples/powertools-examples-idempotency/src/test/java/helloworld/AppTest.java
  examples/powertools-examples-idempotency/src/test/resources/event.json
  examples/powertools-examples-idempotency/template.yaml
  examples/powertools-examples-parameters/README.md
  examples/powertools-examples-parameters/pom.xml
  examples/powertools-examples-parameters/src/main/java/org/demo/parameters/MyObject.java
  examples/powertools-examples-parameters/src/main/java/org/demo/parameters/ParametersFunction.java
  examples/powertools-examples-parameters/src/main/resources/log4j2.xml
  examples/powertools-examples-parameters/template.yaml
  examples/powertools-examples-serialization/README.md
  examples/powertools-examples-serialization/events/APIGatewayEvent.json
  examples/powertools-examples-serialization/events/SQSEvent.json
  examples/powertools-examples-serialization/pom.xml
  examples/powertools-examples-serialization/src/main/java/org/demo/serialization/APIGatewayRequestDeserializationFunction.java
  examples/powertools-examples-serialization/src/main/java/org/demo/serialization/Product.java
  examples/powertools-examples-serialization/src/main/java/org/demo/serialization/SQSEventDeserializationFunction.java
  examples/powertools-examples-serialization/src/main/resources/log4j2.xml
  examples/powertools-examples-serialization/src/test/java/org/demo/serialization/APIGatewayRequestDeserializationFunctionTest.java
  examples/powertools-examples-serialization/src/test/java/org/demo/serialization/SQSEventDeserializationFunctionTest.java
  examples/powertools-examples-serialization/template.yaml
  examples/powertools-examples-sqs/README.md
  examples/powertools-examples-sqs/events/event.json
  examples/powertools-examples-sqs/pom.xml
  examples/powertools-examples-sqs/src/main/java/org/demo/sqs/SqsMessageSender.java
  examples/powertools-examples-sqs/src/main/java/org/demo/sqs/SqsPoller.java
  examples/powertools-examples-sqs/src/main/resources/log4j2.xml
  examples/powertools-examples-sqs/template.yaml
  examples/powertools-examples-validation/README.md
  examples/powertools-examples-validation/events/event.json
  examples/powertools-examples-validation/pom.xml
  examples/powertools-examples-validation/src/main/java/org/demo/validation/InboundValidation.java
  examples/powertools-examples-validation/src/main/resources/schema.json
  examples/powertools-examples-validation/src/test/java/org/demo/validation/InboundValidationTest.java
  examples/powertools-examples-validation/template.yaml
  examples/spotbugs-exclude.xml
  pom.xml
  spotbugs-exclude.xml
Labels: size/XXL

#1060 chore(metrics): deprecate withMetricLogger in favor of withMetricsLogger
  powertools-metrics/src/main/java/software/amazon/lambda/powertools/metrics/MetricsUtils.java
  powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/MetricsLoggerTest.java
Labels: size/M

#1066 docs(plugin): fix mdocs and git revision plugin integration
  .github/workflows/build-docs.yml
  .github/workflows/docs.yml
  mkdocs.yml
Labels: size/S
