Repository aws-powertools/powertools-lambda-java, pull requests merged in 2024-02, with the labels that each got.

#1556 build(deps): bump com.fasterxml.jackson from 2.15.3 to 2.16.0 and com.amazonaws.xray from 2.14.0 to 2.15.0
  pom.xml
Labels: size/XS

#1560 docs(v2): Update README.md
  README.md
Labels: size/XS

#1572 chore: Fix integration tests
  .github/workflows/pr_build.yml
Labels: size/XS

#1574 chore(v2): Merge down from main
  .github/dependabot.yml
  .github/workflows/pr_build.yml
  .github/workflows/pr_iac_lint.yml
  docs/index.md
  examples/powertools-examples-core-utilities/cdk/app/src/main/java/helloworld/AppStream.java
  examples/powertools-examples-core-utilities/cdk/infra/src/test/java/cdk/CdkStackTest.java
  examples/powertools-examples-core-utilities/gradle/src/main/java/helloworld/AppStream.java
  powertools-e2e-tests/handlers/pom.xml
Labels: size/L

#1575 chore(v2): Fix build
  .github/workflows/pr_iac_lint.yml
Labels: size/XS

#1576 chore(v2): Fix IaC lint
  .github/workflows/pr_iac_lint.yml
Labels: size/XS

#1571 chore(v2): e2e tests
  examples/powertools-examples-idempotency/pom.xml
  powertools-e2e-tests/handlers/idempotency/pom.xml
  powertools-e2e-tests/handlers/idempotency/src/main/java/software/amazon/lambda/powertools/e2e/Function.java
  powertools-e2e-tests/handlers/largemessage_idempotent/pom.xml
  powertools-e2e-tests/handlers/largemessage_idempotent/src/main/java/software/amazon/lambda/powertools/e2e/Function.java
  powertools-e2e-tests/handlers/pom.xml
Labels: size/S
