Repository aws-powertools/powertools-lambda-java, pull requests merged in 2024-01, with the labels that each got.

#1545 fix(v2): Removing LambdaJsonLayout from logging config in examples
  examples/powertools-examples-parameters/src/main/resources/log4j2.xml
  examples/powertools-examples-serialization/src/main/resources/log4j2.xml
  powertools-tracing/src/test/resources/log4j2.xml
Labels: size/XS

#1542 chore: Remove empty CDK test
  .github/workflows/pr_iac_lint.yml
  examples/powertools-examples-core/cdk/infra/src/test/java/cdk/CdkStackTest.java
Labels: size/M, priority:3

#1548 chore: dependabot on v2 branch
  .github/dependabot.yml
Labels: size/XS

#1549 fix(v2): Fix params builder to provide default transformation manager
  powertools-parameters/powertools-parameters-appconfig/src/main/java/software/amazon/lambda/powertools/parameters/appconfig/AppConfigProviderBuilder.java
  powertools-parameters/powertools-parameters-appconfig/src/test/java/software/amazon/lambda/powertools/parameters/appconfig/AppConfigProviderTest.java
  powertools-parameters/powertools-parameters-dynamodb/src/main/java/software/amazon/lambda/powertools/parameters/dynamodb/DynamoDbProviderBuilder.java
  powertools-parameters/powertools-parameters-dynamodb/src/test/java/software/amazon/lambda/powertools/parameters/dynamodb/DynamoDbProviderTest.java
  powertools-parameters/powertools-parameters-secrets/src/main/java/software/amazon/lambda/powertools/parameters/secrets/SecretsProviderBuilder.java
  powertools-parameters/powertools-parameters-secrets/src/test/java/software/amazon/lambda/powertools/parameters/secrets/SecretsProviderTest.java
  powertools-parameters/powertools-parameters-ssm/src/main/java/software/amazon/lambda/powertools/parameters/ssm/SSMProviderBuilder.java
  powertools-parameters/powertools-parameters-ssm/src/test/java/software/amazon/lambda/powertools/parameters/ssm/SSMProviderTest.java
Labels: size/M
