Repository aws-powertools/powertools-lambda-java, pull requests merged in 2024-07, with the labels that each got.

#1674 build(deps): bump com.networknt:json-schema-validator from 1.0.87 to 1.4.3
  docs/utilities/validation.md
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/ValidationALBE2ET.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/ValidationApiGWE2ET.java
  powertools-validation/pom.xml
  powertools-validation/src/main/java/software/amazon/lambda/powertools/validation/ValidationConfig.java
  powertools-validation/src/main/java/software/amazon/lambda/powertools/validation/ValidationUtils.java
  powertools-validation/src/test/java/software/amazon/lambda/powertools/validation/ValidationUtilsTest.java
  powertools-validation/src/test/resources/schema_v7.json
  powertools-validation/src/test/resources/schema_v7_ko.json
Labels: size/M

#1624 chore(v2): remove deprecated code
  .github/workflows/build-docs.yml
  .github/workflows/pr_artifacts_size.yml
  .github/workflows/pr_build.yml
  .github/workflows/pr_build_v2.yml
  .github/workflows/pr_iac_lint.yml
  .github/workflows/run-e2e-tests-v2.yml
  .github/workflows/run-e2e-tests.yml
  .github/workflows/spotbugs.yml
  examples/README.md
  powertools-cloudformation/src/main/java/software/amazon/lambda/powertools/cloudformation/Response.java
  powertools-cloudformation/src/test/java/software/amazon/lambda/powertools/cloudformation/CloudFormationResponseTest.java
  powertools-cloudformation/src/test/java/software/amazon/lambda/powertools/cloudformation/ResponseTest.java
  powertools-cloudformation/src/test/java/software/amazon/lambda/powertools/cloudformation/handlers/NoPhysicalResourceIdSetHandler.java
  powertools-metrics/src/main/java/software/amazon/lambda/powertools/metrics/MetricsUtils.java
  powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/MetricsLoggerTest.java
  powertools-tracing/pom.xml
  powertools-tracing/src/main/java/software/amazon/lambda/powertools/tracing/Tracing.java
  powertools-tracing/src/main/java/software/amazon/lambda/powertools/tracing/internal/LambdaTracingAspect.java
  powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/handlers/PowerTracerToolEnabledWithNoMetaDataDeprecated.java
  powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/internal/LambdaTracingAspectTest.java
Labels: size/L, v2, governance

#1686 docs: fix tracing links for xray
  docs/core/tracing.md
Labels: size/XS

#1687 docs: improve tracing doc for sdk instrumentation
  docs/core/tracing.md
Labels: size/S
