Repository aws-powertools/powertools-lambda-java, pull requests merged in 2025-06, with the labels that each got.

#1860 chore(ci): Migrate publishing to Maven Central
  .github/workflows/release.yml
  pom.xml
Labels: size/S, maintenance, governance

#1869 fix(ci): Checkout repo on doc release
  .github/workflows/release.yml
Labels: size/S

#1877 docs: Add versioning plugin for docs and update workflows
  .github/workflows/build-docs.yml
  .github/workflows/release.yml
  docs/overrides/main.html
  mkdocs.yml
Labels: size/L

#1896 docs: Announce deprecation of v1
  docs/processes/versioning.md
  docs/upgrade.md
Labels: documentation, size/S, maintenance

#1891 fix(metrics): Do not flush when no metrics were added to avoid printing root-level _aws dict
  powertools-metrics/src/main/java/software/amazon/lambda/powertools/metrics/internal/EmfMetricsLogger.java
  powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/internal/EmfMetricsLoggerTest.java
Labels: bug, size/S, metrics

#1907 fix(kafka): Handle message indices in proto data also for Glue Schema Registry
  examples/powertools-examples-core-utilities/cdk/app/pom.xml
  examples/powertools-examples-core-utilities/gradle/build.gradle
  examples/powertools-examples-core-utilities/kotlin/build.gradle.kts
  examples/powertools-examples-core-utilities/sam-graalvm/pom.xml
  examples/powertools-examples-core-utilities/sam/pom.xml
  examples/powertools-examples-core-utilities/serverless/pom.xml
  examples/powertools-examples-core-utilities/terraform/pom.xml
  examples/powertools-examples-idempotency/pom.xml
  examples/powertools-examples-kafka/events/kafka-protobuf-event.json
  examples/powertools-examples-kafka/tools/pom.xml
  examples/powertools-examples-kafka/tools/src/main/java/org/demo/kafka/tools/GenerateProtobufSamples.java
  examples/powertools-examples-parameters/sam-graalvm/pom.xml
  examples/powertools-examples-parameters/sam/pom.xml
  examples/powertools-examples-serialization/pom.xml
  pom.xml
  powertools-kafka/src/main/java/software/amazon/lambda/powertools/kafka/serializers/AbstractKafkaDeserializer.java
  powertools-kafka/src/main/java/software/amazon/lambda/powertools/kafka/serializers/KafkaAvroDeserializer.java
  powertools-kafka/src/main/java/software/amazon/lambda/powertools/kafka/serializers/KafkaJsonDeserializer.java
  powertools-kafka/src/main/java/software/amazon/lambda/powertools/kafka/serializers/KafkaProtobufDeserializer.java
  powertools-kafka/src/test/java/software/amazon/lambda/powertools/kafka/serializers/AbstractKafkaDeserializerTest.java
  powertools-kafka/src/test/java/software/amazon/lambda/powertools/kafka/serializers/KafkaAvroDeserializerTest.java
  powertools-kafka/src/test/java/software/amazon/lambda/powertools/kafka/serializers/KafkaJsonDeserializerTest.java
  powertools-kafka/src/test/java/software/amazon/lambda/powertools/kafka/serializers/KafkaProtobufDeserializerTest.java
Labels: feature-request, size/XL, kafka

#1914 chore(ci): Update branch protection rules
  .github/branch_protection_settings/1.x.x.json
  .github/branch_protection_settings/main.json
Labels: size/M
