Repository aws-powertools/powertools-lambda-java, pull requests merged in 2025-05, with the labels that each got.

#1829 fix(ci): minor fixes for workflows
  .github/workflows/check-e2e.yml
  .github/workflows/security-dependencies-check.yml
Labels: size/XS

#1831 fix(ci): Update control flow to allow for better skipping of things
  .github/workflows/release.yml
Labels: size/XS

#1832 fix(ci): Set user/pass for publishing to maven central
  .github/workflows/release.yml
Labels: size/XS

#1845 fix(logging): Escape double-quotes when serializing strings into JSON.
  powertools-logging/powertools-logging-logback/src/test/java/software/amazon/lambda/powertools/logging/internal/LambdaJsonEncoderTest.java
  powertools-logging/src/main/java/software/amazon/lambda/powertools/logging/internal/JsonSerializer.java
Labels: bug, v2, logger

#1824 feat(v2): GraalVM support for parameters module
  examples/pom.xml
  examples/powertools-examples-core-utilities/sam-graalvm/pom.xml
  examples/powertools-examples-parameters/sam-graalvm/Dockerfile
  examples/powertools-examples-parameters/sam-graalvm/Makefile
  examples/powertools-examples-parameters/sam-graalvm/README.md
  examples/powertools-examples-parameters/sam-graalvm/pom.xml
  examples/powertools-examples-parameters/sam-graalvm/src/main/config/bootstrap
  examples/powertools-examples-parameters/sam-graalvm/src/main/java/org/demo/parameters/MyObject.java
  examples/powertools-examples-parameters/sam-graalvm/src/main/java/org/demo/parameters/ParametersFunction.java
  examples/powertools-examples-parameters/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-core/reflect-config.json
  examples/powertools-examples-parameters/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-events/reflect-config.json
  examples/powertools-examples-parameters/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/jni-config.json
  examples/powertools-examples-parameters/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/native-image.properties
  examples/powertools-examples-parameters/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/reflect-config.json
  examples/powertools-examples-parameters/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/resource-config.json
  examples/powertools-examples-parameters/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-serialization/reflect-config.json
  examples/powertools-examples-parameters/sam-graalvm/src/main/resources/META-INF/native-image/helloworld/native-image.properties
  examples/powertools-examples-parameters/sam-graalvm/src/main/resources/META-INF/native-image/helloworld/reflect-config.json
  examples/powertools-examples-parameters/sam-graalvm/src/main/resources/META-INF/native-image/helloworld/resource-config.json
  examples/powertools-examples-parameters/sam-graalvm/src/main/resources/log4j2.xml
  examples/powertools-examples-parameters/sam-graalvm/template.yaml
  examples/powertools-examples-parameters/sam/README.md
  examples/powertools-examples-parameters/sam/pom.xml
  examples/powertools-examples-parameters/sam/src/main/java/org/demo/parameters/MyObject.java
  examples/powertools-examples-parameters/sam/src/main/java/org/demo/parameters/ParametersFunction.java
  examples/powertools-examples-parameters/sam/src/main/resources/log4j2.xml
  examples/powertools-examples-parameters/sam/template.yaml
  powertools-parameters/pom.xml
  powertools-parameters/powertools-parameters-appconfig/pom.xml
  powertools-parameters/powertools-parameters-appconfig/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-parameters-appconfig/jni-config.json
  powertools-parameters/powertools-parameters-appconfig/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-parameters-appconfig/reflect-config.json
  powertools-parameters/powertools-parameters-appconfig/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-parameters-appconfig/resource-config.json
  powertools-parameters/powertools-parameters-dynamodb/pom.xml
  powertools-parameters/powertools-parameters-dynamodb/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-parameters-dynamodb/jni-config.json
  powertools-parameters/powertools-parameters-dynamodb/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-parameters-dynamodb/reflect-config.json
  powertools-parameters/powertools-parameters-dynamodb/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-parameters-dynamodb/resource-config.json
  powertools-parameters/powertools-parameters-secrets/pom.xml
  powertools-parameters/powertools-parameters-secrets/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-parameters-secrets/jni-config.json
  powertools-parameters/powertools-parameters-secrets/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-parameters-secrets/reflect-config.json
  powertools-parameters/powertools-parameters-secrets/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-parameters-secrets/resource-config.json
  powertools-parameters/powertools-parameters-ssm/pom.xml
  powertools-parameters/powertools-parameters-ssm/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-parameters-ssm/jni-config.json
  powertools-parameters/powertools-parameters-ssm/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-parameters-ssm/reflect-config.json
  powertools-parameters/powertools-parameters-ssm/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-parameters-ssm/resource-config.json
  powertools-parameters/powertools-parameters-tests/pom.xml
  powertools-parameters/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-parameters/reflect-config.json
Labels: size/XXL

#1856 docs(v2): Create upgrade guide and versioning policy
  docs/processes/maintainers.md
  docs/processes/versioning.md
  docs/upgrade.md
  docs/utilities/custom_resources.md
  docs/utilities/validation.md
  mkdocs.yml
Labels: documentation, size/XL, v2
