Repository aws-powertools/powertools-lambda-java, pull requests merged in 2025-04, with the labels that each got.

#1816 ci: Fix infrastructure deployment and assertions in end-to-end tests.
  powertools-e2e-tests/handlers/tracing/src/main/java/software/amazon/lambda/powertools/e2e/Function.java
  powertools-e2e-tests/pom.xml
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/LargeMessageE2ET.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/MetricsE2ET.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/TracingE2ET.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/Infrastructure.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/metrics/MetricsFetcher.java
Labels: bug, size/L, maintenance, governance

#1796 docs: Correct XML formatting for Maven configuration in Large Messages utility docs
  docs/utilities/large_messages.md
Labels: size/M

#1739 docs: fix 2 typos
  docs/core/logging.md
  docs/utilities/parameters.md
Labels: size/XS

#1819 docs: v2 documentation maintenance fixing formatting and dependency issues as well as adding roadmap and llms.txt
  .gitignore
  CHANGELOG.md
  README.md
  docs/Dockerfile
  docs/FAQs.md
  docs/core/logging.md
  docs/core/metrics.md
  docs/core/tracing.md
  docs/index.md
  docs/requirements.in
  docs/requirements.txt
  docs/roadmap.md
  docs/utilities/idempotency.md
  docs/utilities/large_messages.md
  docs/utilities/parameters.md
  docs/utilities/validation.md
  mkdocs.yml
Labels: size/XL

#1821 feat(idempotency): Add support for ReturnValuesOnConditionCheckFailure in Idempotency.
  powertools-idempotency/powertools-idempotency-core/src/main/java/software/amazon/lambda/powertools/idempotency/exceptions/IdempotencyItemAlreadyExistsException.java
  powertools-idempotency/powertools-idempotency-core/src/main/java/software/amazon/lambda/powertools/idempotency/internal/IdempotencyHandler.java
  powertools-idempotency/powertools-idempotency-core/src/main/java/software/amazon/lambda/powertools/idempotency/persistence/DataRecord.java
  powertools-idempotency/powertools-idempotency-core/src/test/java/software/amazon/lambda/powertools/idempotency/internal/IdempotencyAspectTest.java
  powertools-idempotency/powertools-idempotency-dynamodb/src/main/java/software/amazon/lambda/powertools/idempotency/persistence/dynamodb/DynamoDBPersistenceStore.java
  powertools-idempotency/powertools-idempotency-dynamodb/src/test/java/software/amazon/lambda/powertools/idempotency/persistence/dynamodb/DynamoDBConfig.java
  powertools-idempotency/powertools-idempotency-dynamodb/src/test/java/software/amazon/lambda/powertools/idempotency/persistence/dynamodb/DynamoDBPersistenceStoreTest.java
  powertools-idempotency/powertools-idempotency-dynamodb/src/test/java/software/amazon/lambda/powertools/idempotency/persistence/dynamodb/IdempotencyTest.java
  powertools-idempotency/powertools-idempotency-dynamodb/src/test/java/software/amazon/lambda/powertools/idempotency/persistence/dynamodb/handlers/IdempotencyFunction.java
Labels: size/L, feature-parity, idempotency

#1823 docs: Add version policy page and llms.txt, enable privacy plugin, fix formatting
  .gitignore
  docs/processes/versioning.md
  docs/requirements.in
  docs/requirements.txt
  docs/roadmap.md
  docs/utilities/validation.md
  mkdocs.yml
Labels: size/L
