Repository aws-powertools/powertools-lambda-java, pull requests merged in 2025-08, with the labels that each got.

#2022 docs(examples): Add Bazel example for core utilities
  examples/powertools-examples-core-utilities/sam-bazel/.bazelrc
  examples/powertools-examples-core-utilities/sam-bazel/.gitignore
  examples/powertools-examples-core-utilities/sam-bazel/BUILD.bazel
  examples/powertools-examples-core-utilities/sam-bazel/MODULE.bazel
  examples/powertools-examples-core-utilities/sam-bazel/README.md
  examples/powertools-examples-core-utilities/sam-bazel/events/event.json
  examples/powertools-examples-core-utilities/sam-bazel/src/main/java/helloworld/App.java
  examples/powertools-examples-core-utilities/sam-bazel/src/main/java/helloworld/AppStream.java
  examples/powertools-examples-core-utilities/sam-bazel/src/main/resources/log4j2.xml
  examples/powertools-examples-core-utilities/sam-bazel/template.yaml
Labels: documentation, size/XL

#2018 chore(ci): Improve reliability of retries in TracingE2ET
  powertools-e2e-tests/pom.xml
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/MetricsE2ET.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/RetryUtils.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/tracing/TraceFetcher.java
Labels: size/L, maintenance, governance

#2044 chore(ci): Remove non-PR triggers for verify dependencies workflow.
  .github/workflows/security-dependencies-check.yml
Labels: size/S, governance

#2053 fix(ci): Update branch protection output
  .github/branch_protection_settings/main.json
Labels: size/XS

#2063 chore(ci): Add powertools-e2e-tests/handlers as module to capture it in GitHub actions version upgrades.
  examples/powertools-examples-kafka/src/main/java/org/demo/kafka/protobuf/ProtobufProduct.java
  examples/powertools-examples-kafka/src/main/java/org/demo/kafka/protobuf/ProtobufProductOrBuilder.java
  examples/powertools-examples-kafka/src/main/java/org/demo/kafka/protobuf/ProtobufProductOuterClass.java
  pom.xml
  powertools-e2e-tests/handlers/batch/pom.xml
  powertools-e2e-tests/handlers/idempotency/pom.xml
  powertools-e2e-tests/handlers/largemessage/pom.xml
  powertools-e2e-tests/handlers/largemessage_idempotent/pom.xml
  powertools-e2e-tests/handlers/logging/pom.xml
  powertools-e2e-tests/handlers/metrics/pom.xml
  powertools-e2e-tests/handlers/parameters/pom.xml
  powertools-e2e-tests/handlers/pom.xml
  powertools-e2e-tests/handlers/tracing/pom.xml
  powertools-e2e-tests/handlers/validation-alb-event/pom.xml
  powertools-e2e-tests/handlers/validation-apigw-event/pom.xml
  powertools-e2e-tests/pom.xml
Labels: size/M, maintenance, governance

#2076 chore(ci): Fix issue where docs were released with old version during release
  .github/workflows/release.yml
Labels: size/XS

#2047 chore(ci): Run unit tests for GraalVM as well during build.
  .github/dependency-review-config.yml
  .github/workflows/check-build.yml
  pom.xml
  powertools-common/pom.xml
  powertools-common/src/test/java/software/amazon/lambda/powertools/common/internal/LambdaHandlerProcessorTest.java
  powertools-common/src/test/java/software/amazon/lambda/powertools/common/stubs/TestLambdaContext.java
  powertools-logging/pom.xml
  powertools-logging/powertools-logging-log4j/pom.xml
  powertools-logging/powertools-logging-log4j/src/test/java/org/apache/logging/log4j/layout/template/json/resolver/PowerToolsResolverFactoryTest.java
  powertools-logging/powertools-logging-log4j/src/test/java/org/apache/logging/log4j/layout/template/json/resolver/PowertoolsResolverArgumentsTest.java
  powertools-logging/powertools-logging-logback/pom.xml
  powertools-logging/powertools-logging-logback/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-logging-logback/jni-config.json
  powertools-logging/powertools-logging-logback/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-logging-logback/reflect-config.json
  powertools-logging/powertools-logging-logback/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-logging-logback/resource-config.json
  powertools-logging/powertools-logging-logback/src/test/java/software/amazon/lambda/powertools/logging/internal/LambdaEcsEncoderTest.java
  powertools-logging/powertools-logging-logback/src/test/java/software/amazon/lambda/powertools/logging/internal/LambdaJsonEncoderTest.java
  powertools-logging/src/test/java/software/amazon/lambda/powertools/logging/internal/LambdaLoggingAspectTest.java
  powertools-metrics/pom.xml
  powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/ConfigurationPrecedenceTest.java
  powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/internal/EmfMetricsLoggerTest.java
  powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/internal/LambdaMetricsAspectTest.java
  powertools-parameters/pom.xml
  powertools-parameters/powertools-parameters-appconfig/pom.xml
  powertools-parameters/powertools-parameters-appconfig/src/test/java/software/amazon/lambda/powertools/parameters/appconfig/AppConfigParamAspectTest.java
  powertools-parameters/powertools-parameters-appconfig/src/test/java/software/amazon/lambda/powertools/parameters/appconfig/AppConfigProviderTest.java
  powertools-parameters/powertools-parameters-dynamodb/pom.xml
  powertools-parameters/powertools-parameters-dynamodb/src/test/java/software/amazon/lambda/powertools/parameters/dynamodb/DynamoDbProviderTest.java
  powertools-parameters/powertools-parameters-secrets/pom.xml
  powertools-parameters/powertools-parameters-secrets/src/test/java/software/amazon/lambda/powertools/parameters/secrets/SecretsProviderTest.java
  powertools-parameters/powertools-parameters-ssm/pom.xml
  powertools-parameters/powertools-parameters-tests/pom.xml
  powertools-parameters/powertools-parameters-tests/src/test/java/software/amazon/lambda/powertools/parameters/BaseProviderTest.java
  powertools-parameters/powertools-parameters-tests/src/test/java/software/amazon/lambda/powertools/parameters/ParamProvidersIntegrationTest.java
  powertools-serialization/pom.xml
  powertools-tracing/pom.xml
  powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/TracingUtilsTest.java
  powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/internal/LambdaTracingAspectTest.java
Labels: size/XXL, governance, graalvm, do-not-merge

#2080 feat(graalvm): GraalVM support for Idempotency utility
  .github/workflows/check-build.yml
  examples/README.md
  examples/pom.xml
  examples/powertools-examples-idempotency/sam-graalvm/Dockerfile
  examples/powertools-examples-idempotency/sam-graalvm/Makefile
  examples/powertools-examples-idempotency/sam-graalvm/README.md
  examples/powertools-examples-idempotency/sam-graalvm/pom.xml
  examples/powertools-examples-idempotency/sam-graalvm/src/main/config/bootstrap
  examples/powertools-examples-idempotency/sam-graalvm/src/main/java/helloworld/App.java
  examples/powertools-examples-idempotency/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-core/reflect-config.json
  examples/powertools-examples-idempotency/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-events/reflect-config.json
  examples/powertools-examples-idempotency/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/jni-config.json
  examples/powertools-examples-idempotency/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/native-image.properties
  examples/powertools-examples-idempotency/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/reflect-config.json
  examples/powertools-examples-idempotency/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/resource-config.json
  examples/powertools-examples-idempotency/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-serialization/reflect-config.json
  examples/powertools-examples-idempotency/sam-graalvm/src/main/resources/META-INF/native-image/helloworld/reflect-config.json
  examples/powertools-examples-idempotency/sam-graalvm/src/main/resources/META-INF/native-image/helloworld/resource-config.json
  examples/powertools-examples-idempotency/sam-graalvm/src/main/resources/log4j2.xml
  examples/powertools-examples-idempotency/sam-graalvm/template.yaml
  examples/powertools-examples-idempotency/sam/README.md
  examples/powertools-examples-idempotency/sam/pom.xml
  examples/powertools-examples-idempotency/sam/src/main/java/helloworld/App.java
  examples/powertools-examples-idempotency/sam/src/main/resources/log4j2.xml
  examples/powertools-examples-idempotency/sam/template.yaml
  pom.xml
  powertools-e2e-tests/handlers/idempotency/pom.xml
  powertools-e2e-tests/handlers/idempotency/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-core/reflect-config.json
  powertools-e2e-tests/handlers/idempotency/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-events/reflect-config.json
  powertools-e2e-tests/handlers/idempotency/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/jni-config.json
  powertools-e2e-tests/handlers/idempotency/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/native-image.properties
  powertools-e2e-tests/handlers/idempotency/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/reflect-config.json
  powertools-e2e-tests/handlers/idempotency/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/resource-config.json
  powertools-e2e-tests/handlers/idempotency/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-serialization/reflect-config.json
  powertools-e2e-tests/handlers/idempotency/src/main/resources/META-INF/native-image/software.amazon.lambda.powertools.e2e/reflect-config.json
  powertools-e2e-tests/handlers/idempotency/src/main/resources/META-INF/native-image/software.amazon.lambda.powertools.e2e/resource-config.json
  powertools-e2e-tests/pom.xml
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/IdempotencyE2ET.java
  powertools-e2e-tests/src/test/java/software/amazon/lambda/powertools/testutils/DockerConfiguration.java
  powertools-idempotency/powertools-idempotency-core/pom.xml
  powertools-idempotency/powertools-idempotency-core/src/test/java/software/amazon/lambda/powertools/idempotency/internal/IdempotencyAspectTest.java
  powertools-idempotency/powertools-idempotency-core/src/test/java/software/amazon/lambda/powertools/idempotency/internal/cache/LRUCacheTest.java
  powertools-idempotency/powertools-idempotency-core/src/test/java/software/amazon/lambda/powertools/idempotency/persistence/BasePersistenceStoreTest.java
  powertools-idempotency/powertools-idempotency-core/src/test/resources/simplelogger.properties
  powertools-idempotency/powertools-idempotency-dynamodb/dynamodb-local-metadata.json
  powertools-idempotency/powertools-idempotency-dynamodb/pom.xml
  powertools-idempotency/powertools-idempotency-dynamodb/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-idempotency-dynamodb/reflect-config.json
  powertools-idempotency/powertools-idempotency-dynamodb/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-idempotency-dynamodb/resource-config.json
  powertools-idempotency/powertools-idempotency-dynamodb/src/test/java/software/amazon/lambda/powertools/idempotency/persistence/dynamodb/DynamoDBConfig.java
  powertools-idempotency/powertools-idempotency-dynamodb/src/test/java/software/amazon/lambda/powertools/idempotency/persistence/dynamodb/DynamoDBPersistenceStoreTest.java
  powertools-idempotency/powertools-idempotency-dynamodb/src/test/java/software/amazon/lambda/powertools/idempotency/persistence/dynamodb/IdempotencyTest.java
  powertools-idempotency/powertools-idempotency-dynamodb/src/test/resources/simplelogger.properties
Labels: size/XXL
