Repository aws-powertools/powertools-lambda-java, pull requests merged in 2025-03, with the labels that each got.

#1792 fix(ci): Add workflow_dispatch to build script
  .github/workflows/pr_build.yml
Labels: size/XS

#1791 chore(deps): update JSII to 1.108
  examples/powertools-examples-core/cdk/infra/pom.xml
  tree.txt
Labels: size/L

#1793 chore(deps): Update deps for jackson
  examples/powertools-examples-core/cdk/app/pom.xml
  examples/powertools-examples-core/cdk/infra/pom.xml
  powertools-logging/pom.xml
  tree.txt
Labels: size/L

#1795 chore(ci): Update release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: size/XS

#1753 feat(v2): Add GraalVM reachability metadata for core utilities
  GraalVM.md
  docs/FAQs.md
  docs/core/logging.md
  examples/powertools-examples-core-utilities/sam-graalvm/Dockerfile
  examples/powertools-examples-core-utilities/sam-graalvm/Makefile
  examples/powertools-examples-core-utilities/sam-graalvm/README.md
  examples/powertools-examples-core-utilities/sam-graalvm/events/event.json
  examples/powertools-examples-core-utilities/sam-graalvm/pom.xml
  examples/powertools-examples-core-utilities/sam-graalvm/src/main/config/bootstrap
  examples/powertools-examples-core-utilities/sam-graalvm/src/main/java/helloworld/App.java
  examples/powertools-examples-core-utilities/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-core/reflect-config.json
  examples/powertools-examples-core-utilities/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-events/reflect-config.json
  examples/powertools-examples-core-utilities/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/jni-config.json
  examples/powertools-examples-core-utilities/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/native-image.properties
  examples/powertools-examples-core-utilities/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/reflect-config.json
  examples/powertools-examples-core-utilities/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/resource-config.json
  examples/powertools-examples-core-utilities/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-serialization/reflect-config.json
  examples/powertools-examples-core-utilities/sam-graalvm/src/main/resources/META-INF/native-image/helloworld/native-image.properties
  examples/powertools-examples-core-utilities/sam-graalvm/src/main/resources/META-INF/native-image/helloworld/reflect-config.json
  examples/powertools-examples-core-utilities/sam-graalvm/src/main/resources/META-INF/native-image/helloworld/resource-config.json
  examples/powertools-examples-core-utilities/sam-graalvm/src/main/resources/log4j2.xml
  examples/powertools-examples-core-utilities/sam-graalvm/template.yaml
  pom.xml
  powertools-common/pom.xml
  powertools-common/src/main/java/software/amazon/lambda/powertools/common/internal/UserAgentConfigurator.java
  powertools-common/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-common/jni-config.json
  powertools-common/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-common/reflect-config.json
  powertools-common/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-common/resource-config.json
  powertools-common/src/test/java/software/amazon/lambda/powertools/common/internal/LambdaHandlerProcessorTest.java
  powertools-common/src/test/java/software/amazon/lambda/powertools/common/internal/UserAgentConfiguratorTest.java
  powertools-common/src/test/resources/unreadable.properties
  powertools-logging/pom.xml
  powertools-logging/powertools-logging-log4j/pom.xml
  powertools-logging/powertools-logging-log4j/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-logging-log4j/jni-config.json
  powertools-logging/powertools-logging-log4j/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-logging-log4j/reflect-config.json
  powertools-logging/powertools-logging-log4j/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-logging-log4j/resource-config.json
  powertools-logging/powertools-logging-log4j/src/test/java/org/apache/logging/log4j/layout/template/json/resolver/PowertoolsResolverTest.java
  powertools-logging/powertools-logging-logback/pom.xml
  powertools-logging/powertools-logging-logback/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-logging-logback/jni-config.json
  powertools-logging/powertools-logging-logback/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-logging-logback/reflect-config.json
  powertools-logging/powertools-logging-logback/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-logging-logback/resource-config.json
  powertools-logging/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-logging/jni-config.json
  powertools-logging/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-logging/reflect-config.json
  powertools-logging/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-logging/resource-config.json
  powertools-logging/src/test/java/software/amazon/lambda/powertools/logging/internal/LambdaLoggingAspectTest.java
  powertools-metrics/pom.xml
  powertools-metrics/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-metrics/jni-config.json
  powertools-metrics/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-metrics/reflect-config.json
  powertools-metrics/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-metrics/resource-config.json
  powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/MetricsLoggerTest.java
  powertools-metrics/src/test/java/software/amazon/lambda/powertools/metrics/internal/LambdaMetricsAspectTest.java
  powertools-serialization/pom.xml
  powertools-serialization/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-serialization/jni-config.json
  powertools-serialization/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-serialization/reflect-config.json
  powertools-serialization/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-serialization/resource-config.json
  powertools-tracing/pom.xml
  powertools-tracing/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-tracing/jni-config.json
  powertools-tracing/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-tracing/reflect-config.json
  powertools-tracing/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-tracing/resource-config.json
  powertools-tracing/src/test/java/software/amazon/lambda/powertools/tracing/internal/LambdaTracingAspectTest.java
Labels: size/XXL

#1758 feat(cfn-custom-resource): Add optional 'reason' field for detailed failure reporting
  examples/powertools-examples-core/kotlin/build.gradle.kts
  powertools-cloudformation/src/main/java/software/amazon/lambda/powertools/cloudformation/CloudFormationResponse.java
  powertools-cloudformation/src/main/java/software/amazon/lambda/powertools/cloudformation/Response.java
  powertools-cloudformation/src/test/java/software/amazon/lambda/powertools/cloudformation/CloudFormationResponseTest.java
  powertools-cloudformation/src/test/java/software/amazon/lambda/powertools/cloudformation/ResponseTest.java
Labels: feature-request, size/M

#1813 fix: Load version.properties file as resource stream to fix loading when packaged as jar
  powertools-core/src/main/java/software/amazon/lambda/powertools/core/internal/UserAgentConfigurator.java
Labels: size/M

#1814 feat(idempotency): Add response hook feature
  docs/utilities/idempotency.md
  examples/powertools-examples-idempotency/src/main/java/helloworld/App.java
  powertools-idempotency/powertools-idempotency-core/src/main/java/software/amazon/lambda/powertools/idempotency/IdempotencyConfig.java
  powertools-idempotency/powertools-idempotency-core/src/main/java/software/amazon/lambda/powertools/idempotency/internal/IdempotencyHandler.java
  powertools-idempotency/powertools-idempotency-core/src/test/java/software/amazon/lambda/powertools/idempotency/internal/IdempotencyAspectTest.java
Labels: size/L
