Repository aws-powertools/powertools-lambda-java, pull requests merged in 2025-02, with the labels that each got.

#1762 docs: add roadmap page and include roadmap for 2025
  docs/FAQs.md
  docs/roadmap.md
  mkdocs.yml
Labels: size/L

#1764 chore(ci): update permissions
  .github/workflows/build-docs.yml
  .github/workflows/dispatch_analytics.yml
  .github/workflows/docs.yml
  .github/workflows/pr_artifacts_size.yml
  .github/workflows/pr_build.yml
  .github/workflows/pr_build_v2.yml
  .github/workflows/pr_iac_lint.yml
  .github/workflows/publish.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release-prep.yml
  .github/workflows/run-e2e-tests-v2.yml
  .github/workflows/run-e2e-tests.yml
  .github/workflows/secure_workflows.yml
  .github/workflows/spotbugs.yml
Labels: size/M

#1767 chore: Set versions of transitive dependencies
  examples/pom.xml
  examples/powertools-examples-batch/pom.xml
  examples/powertools-examples-cloudformation/pom.xml
  examples/powertools-examples-core/cdk/app/pom.xml
  examples/powertools-examples-core/cdk/infra/pom.xml
  examples/powertools-examples-core/gradle/build.gradle
  examples/powertools-examples-core/kotlin/build.gradle.kts
  examples/powertools-examples-core/sam/pom.xml
  examples/powertools-examples-core/serverless/pom.xml
  examples/powertools-examples-core/terraform/pom.xml
  examples/powertools-examples-idempotency/pom.xml
  examples/powertools-examples-parameters/pom.xml
  examples/powertools-examples-serialization/pom.xml
  examples/powertools-examples-sqs/pom.xml
  examples/powertools-examples-validation/pom.xml
  pom.xml
  powertools-batch/pom.xml
  powertools-cloudformation/pom.xml
  powertools-core/pom.xml
  powertools-e2e-tests/handlers/batch/pom.xml
  powertools-e2e-tests/handlers/largemessage/pom.xml
  powertools-e2e-tests/handlers/logging/pom.xml
  powertools-e2e-tests/handlers/parameters/pom.xml
  powertools-e2e-tests/handlers/pom.xml
  powertools-e2e-tests/handlers/tracing/pom.xml
  powertools-e2e-tests/pom.xml
  powertools-idempotency/pom.xml
  powertools-large-messages/pom.xml
  powertools-logging/pom.xml
  powertools-metrics/pom.xml
  powertools-parameters/pom.xml
  powertools-serialization/pom.xml
  powertools-sqs/pom.xml
  powertools-test-suite/pom.xml
  powertools-tracing/pom.xml
  powertools-validation/pom.xml
Labels: size/L

#1768 chore: Update netty version
  examples/powertools-examples-batch/pom.xml
Labels: size/S

#1769 fix(ci): OSSF Changes
  .github/workflows/osv.yml
  .github/workflows/pr_build.yml
  docs/Dockerfile
  docs/requirements.in
  docs/requirements.txt
  examples/powertools-examples-core/gradle/gradle/wrapper/gradle-wrapper.jar
  examples/powertools-examples-core/gradle/gradle/wrapper/gradle-wrapper.properties
  examples/powertools-examples-core/kotlin/gradle/wrapper/gradle-wrapper.properties
Labels: size/L

#1770 build(deps): Fix Jackson version to max allowed by JSII
  examples/powertools-examples-core/cdk/infra/pom.xml
Labels: size/S

#1772 chore(ci): Remove RELEASE variable
  .github/workflows/release-prep.yml
Labels: size/XS

#1774 Release permissions
  .github/workflows/publish.yml
  .gitignore
  tree.txt
Labels: size/XXL
