Repository aws-powertools/powertools-lambda-java, pull requests merged in 2025-07, with the labels that each got.

#1905 feat(serialization): Add GraalVM metadata configuration
  examples/pom.xml
  examples/powertools-examples-serialization/sam-graalvm/Dockerfile
  examples/powertools-examples-serialization/sam-graalvm/Makefile
  examples/powertools-examples-serialization/sam-graalvm/README.md
  examples/powertools-examples-serialization/sam-graalvm/events/APIGatewayEvent.json
  examples/powertools-examples-serialization/sam-graalvm/events/SQSEvent.json
  examples/powertools-examples-serialization/sam-graalvm/pom.xml
  examples/powertools-examples-serialization/sam-graalvm/src/main/config/bootstrap
  examples/powertools-examples-serialization/sam-graalvm/src/main/java/org/demo/serialization/APIGatewayRequestDeserializationFunction.java
  examples/powertools-examples-serialization/sam-graalvm/src/main/java/org/demo/serialization/Product.java
  examples/powertools-examples-serialization/sam-graalvm/src/main/java/org/demo/serialization/SQSEventDeserializationFunction.java
  examples/powertools-examples-serialization/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-core/reflect-config.json
  examples/powertools-examples-serialization/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-events/reflect-config.json
  examples/powertools-examples-serialization/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/jni-config.json
  examples/powertools-examples-serialization/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/native-image.properties
  examples/powertools-examples-serialization/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/reflect-config.json
  examples/powertools-examples-serialization/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/resource-config.json
  examples/powertools-examples-serialization/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-serialization/reflect-config.json
  examples/powertools-examples-serialization/sam-graalvm/src/main/resources/META-INF/native-image/helloworld/native-image.properties
  examples/powertools-examples-serialization/sam-graalvm/src/main/resources/META-INF/native-image/helloworld/reflect-config.json
  examples/powertools-examples-serialization/sam-graalvm/src/main/resources/META-INF/native-image/helloworld/resource-config.json
  examples/powertools-examples-serialization/sam-graalvm/src/main/resources/log4j2.xml
  examples/powertools-examples-serialization/sam-graalvm/template.yaml
  examples/powertools-examples-serialization/sam/README.md
  examples/powertools-examples-serialization/sam/events/APIGatewayEvent.json
  examples/powertools-examples-serialization/sam/events/SQSEvent.json
  examples/powertools-examples-serialization/sam/pom.xml
  examples/powertools-examples-serialization/sam/src/main/java/org/demo/serialization/APIGatewayRequestDeserializationFunction.java
  examples/powertools-examples-serialization/sam/src/main/java/org/demo/serialization/Product.java
  examples/powertools-examples-serialization/sam/src/main/java/org/demo/serialization/SQSEventDeserializationFunction.java
  examples/powertools-examples-serialization/sam/src/main/resources/log4j2.xml
  examples/powertools-examples-serialization/sam/template.yaml
  powertools-serialization/pom.xml
  powertools-serialization/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-serialization/jni-config.json
  powertools-serialization/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-serialization/reflect-config.json
  powertools-serialization/src/main/resources/META-INF/native-image/software.amazon.lambda/powertools-serialization/resource-config.json
  powertools-serialization/src/test/resources/META-INF/native-image/software.amazon.lambda/powertools-serialization/reflect-config.json
  powertools-serialization/src/test/resources/META-INF/native-image/software.amazon.lambda/powertools-serialization/resource-config.json
Labels: size/XL

#1935 fix(examples): Fix GraalVM metadata after common runtime client changes
  examples/powertools-examples-core-utilities/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/jni-config.json
  examples/powertools-examples-core-utilities/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/reflect-config.json
  examples/powertools-examples-core-utilities/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/resource-config.json
  examples/powertools-examples-parameters/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/jni-config.json
  examples/powertools-examples-parameters/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/reflect-config.json
  examples/powertools-examples-parameters/sam-graalvm/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-runtime-interface-client/resource-config.json
Labels: size/M

#1948 chore(ci): add new dependabot package ecosystems
  .github/dependabot.yml
Labels: size/S

#1995 docs(examples): Enable end to end tracing for SQS batch example.
  examples/powertools-examples-batch/deploy/sqs/template.yml
  examples/powertools-examples-batch/src/main/java/org/demo/batch/sqs/AbstractSqsBatchHandler.java
Labels: bug, size/S

#1861 feat: Support CRaC and priming of powertools metrics and idempotency-dynamodb
  Priming.md
  pom.xml
  powertools-common/src/main/java/software/amazon/lambda/powertools/common/internal/ClassPreLoader.java
  powertools-common/src/test/java/software/amazon/lambda/powertools/common/internal/ClassPreLoaderTest.java
  powertools-common/src/test/resources/classesloaded.txt
  powertools-idempotency/powertools-idempotency-dynamodb/pom.xml
  powertools-idempotency/powertools-idempotency-dynamodb/src/main/java/software/amazon/lambda/powertools/idempotency/persistence/dynamodb/DynamoDBPersistenceStore.java
  powertools-logging/powertools-logging-logback/src/test/java/software/amazon/lambda/powertools/logging/internal/LambdaJsonEncoderTest.java
  powertools-metrics/pom.xml
  powertools-metrics/src/main/java/software/amazon/lambda/powertools/metrics/MetricsFactory.java
  powertools-metrics/src/main/resources/classesloaded.txt
Labels: size/XXL
